### ISSUE TITLE
Pinch to zoom out does not work on safari

### ISSUE THREAD

**Issue by coinhu1995** [appium/WebDriverAgent#274]
I used pinch to zoom in, zoom out in the Photos application and it worked. When I tried in the safari application, zoom in worked but zoom out did not work

**Comment by electricbubble** [comment]
In practice, the default zoom out moves from the upper-left and lower-right coordinates to the central coordinate point at the same time.

I find it doesn't work in some cases.

So, I tried the following way to implement it.

You can try it, too.

```http
Method: POST
URL: http://localhost:8100/session/$SESSION_ID/actions
Body: {
    "actions": [{
        "type": "pointer",
        "id": "finger1",
        "parameters": {
            "pointerType": "touch"
        },
        "actions": [{
            "type": "pointerMove",
            "origin": "$ELEMENT_ID",
            "x": -75,
            "y": -185,
            "duration": 0
        }, {
            "type": "pointerDown"
        }, {
            "type": "pause",
            "duration": 100
        }, {
            "type": "pointerMove",
            "origin": "$ELEMENT_ID",
            "x": 0,
            "y": 0,
            "duration": 0
        }, {
            "type": "pause",
            "duration": 100
        }, {
            "type": "pointerUp"
        }]
    }, {
        "type": "pointer",
        "id": "finger2",
        "parameters": {
            "pointerType": "touch"
        },
        "actions": [{
            "type": "pointerMove",
            "origin": "$ELEMENT_ID",
            "x": 75,
            "y": 185,
            "duration": 0
        }, {
            "type": "pointerDown"
        }, {
            "type": "pause",
            "duration": 100
        }, {
            "type": "pointerMove",
            "origin": "$ELEMENT_ID",
            "x": 0,
            "y": 0,
            "duration": 0
        }, {
            "type": "pause",
            "duration": 100
        }, {
            "type": "pointerUp"
        }]
    }]
}
```

**Comment by coinhu1995** [comment]
> In practice, the default zoom out moves from both upper-left and upper-right coordinates to the center coordinate point.
> 
> I find it doesn't work in some cases.
> 
> So, I tried the following way to implement it.
> 
> You can try it, too.
> 
> ```httpspec
> Method: POST
> URL: http://localhost:8100/session/$SESSION_ID/actions
> Body: {
>     "actions": [{
>         "type": "pointer",
>         "id": "finger1",
>         "parameters": {
>             "pointerType": "touch"
>         },
>         "actions": [{
>             "type": "pointerMove",
>             "origin": "$ELEMENT_ID",
>             "x": -75,
>             "y": -185,
>             "duration": 0
>         }, {
>             "type": "pointerDown"
>         }, {
>             "type": "pause",
>             "duration": 100
>         }, {
>             "type": "pointerMove",
>             "origin": "$ELEMENT_ID",
>             "x": 0,
>             "y": 0,
>             "duration": 0
>         }, {
>             "type": "pause",
>             "duration": 100
>         }, {
>             "type": "pointerUp"
>         }]
>     }, {
>         "type": "pointer",
>         "id": "finger2",
>         "parameters": {
>             "pointerType": "touch"
>         },
>         "actions": [{
>             "type": "pointerMove",
>             "origin": "$ELEMENT_ID",
>             "x": 75,
>             "y": 185,
>             "duration": 0
>         }, {
>             "type": "pointerDown"
>         }, {
>             "type": "pause",
>             "duration": 100
>         }, {
>             "type": "pointerMove",
>             "origin": "$ELEMENT_ID",
>             "x": 0,
>             "y": 0,
>             "duration": 0
>         }, {
>             "type": "pause",
>             "duration": 100
>         }, {
>             "type": "pointerUp"
>         }]
>     }]
> }
> ```

Thanks @ElectricBubble I will try

**Comment by coinhu1995** [comment]
Hi @ElectricBubble Can we zoom out without element_id, just with the coordinate ?

**Comment by electricbubble** [comment]
> Hi @ElectricBubble Can we zoom out without element_id, just with the coordinate ?

just remove ‘origin‘

**Comment by coinhu1995** [comment]
@ElectricBubble after removed origin, it become a swipe action

**Comment by electricbubble** [comment]
@nhunh585

After removing 'origin', you need to use absolute coordinates, like this:

```json
{
    "width" : 375,
    "height" : 667
  }
```

The central coordinate is `(187.5, 333.5)`

```json
{
    "actions": [{
        "actions": [{
            "type": "pointerMove",
            "x": 137.5,                                         // 187.5-50
            "y": 283.5                                          // 333.5-50
        }, {
            "type": "pointerDown"
        }, {
            "duration": 250,
            "type": "pause"
        }, {
            "type": "pointerMove",
            "x": 187.5,
            "y": 333.5
        }, {
            "duration": 250,
            "type": "pause"
        }, {
            "type": "pointerUp"
        }],
        "id": "finger1",
        "parameters": {
            "pointerType": "touch"
        },
        "type": "pointer"
    }, {
        "actions": [{
            "type": "pointerMove",
            "x": 237.5,                                         // 187.5+50
            "y": 383.5                                          // 333.5+50
        }, {
            "type": "pointerDown"
        }, {
            "duration": 250,
            "type": "pause"
        }, {
            "type": "pointerMove",
            "x": 187.5,
            "y": 333.5
        }, {
            "duration": 250,
            "type": "pause"
        }, {
            "type": "pointerUp"
        }],
        "id": "finger2",
        "parameters": {
            "pointerType": "touch"
        },
        "type": "pointer"
    }]
}
```

![20200510](https://user-images.githubusercontent.com/42672996/81492953-e28c8680-92ce-11ea-8c2f-b288765d3300.gif)

**Comment by tulasikrishan89** [comment]
can you please share request body for zoom-out
