### ISSUE TITLE
Can you build older WDA with newer Xcode ? 

### ISSUE THREAD

**Issue by Arrognz** [appium/WebDriverAgent#299]
Hello :) I was wondering if it was possible to build WDA version 1.3.5 using Xcode11 ? 
I am encountering errors, but I was wondering if maybe there were additional options to use to make it build ? 

Thank you for your time !

**Comment by KazuCocoa** [comment]
No, in general.
We announced which Appium version support which Xcode version. They have/had fixes for newer Xcode versions. https://github.com/appium/appium/releases
