### ISSUE TITLE
iOS 13.4， /window/size return width as 0, height as 0

### ISSUE THREAD

**Issue by ting81** [appium/WebDriverAgent#312]
**Warning:**

Query:
http://localhost:8100/session/DC3DD155-6B13-47DF-9F20-87B145D9F83F/window/size
Return:
{
value: {
width: 0,
height: 0,
},
sessionId: "DC3DD155-6B13-47DF-9F20-87B145D9F83F",
}

These issues are not tracked. Please create new issues in the main Appium
repository: https://github.com/appium/appium/issues/new

**Comment by imurchie** [comment]
Without context of what you're doing, this is hard to approach.

It works for me, though, which is about as useful
```
dbug [08-10-57:126] WD Proxy Proxying [GET /window/size] to [GET http://127.0.0.1:8100/session/BDAFB895-AE95-47F2-9DFA-93463E729B9D/window/size] with no body
dbug [08-10-57:210] WD Proxy Got response with status 200: {
dbug [08-10-57:210] WD Proxy   "value" : {
dbug [08-10-57:210] WD Proxy     "width" : 375,
dbug [08-10-57:210] WD Proxy     "height" : 812
dbug [08-10-57:210] WD Proxy   },
dbug [08-10-57:210] WD Proxy   "sessionId" : "BDAFB895-AE95-47F2-9DFA-93463E729B9D"
dbug [08-10-57:210] WD Proxy }
dbug [08-10-57:211] MJSONWP (7131d7e1) Responding to client with driver.getWindowSize() result: {"width":375,"height":812}
```

**Comment by KazuCocoa** [comment]
I also could not replicate this issue.
Please create a new issue on https://github.com/appium/appium/issues/new when you are still happening the issue.
