### ISSUE TITLE
iOS 13.4.1, query /status, the ip is not the en0, actually it is en1, it seems the sequence of ethernet port is changed

### ISSUE THREAD

**Issue by ting81** [appium/WebDriverAgent#313]
**Warning:**

suggest to modify the code as:
![image](https://user-images.githubusercontent.com/13032174/78965813-b8f60900-7b30-11ea-9bf4-5cee1629a792.png)

These issues are not tracked. Please create new issues in the main Appium
repository: https://github.com/appium/appium/issues/new

**Comment by KazuCocoa** [comment]
What version did you use?
https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIDevice+FBHelpers.m#L185 Current our implementation is `en`
