### ISSUE TITLE
wad build failed bundle id is added .xctrunner auto

### ISSUE THREAD

**Issue by dabaibiao** [appium/WebDriverAgent#344]
_**Mac:10.15.5
Xcode:11.15
wad:appium-WebDriverAgent 2.17.3
using devoper acount not Apple ID
build webdriveragentrunner failed with_:**error: Provisioning profile "com.123" has app ID "com.123", which does not match the bundle ID "com.123.xctrunner". (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
error: Provisioning profile "com.123" doesn't match the entitlements file's value for the application-identifier entitlement. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')

**Comment by KazuCocoa** [comment]
The behavior is expected since Xcode 11. You can avoid the behaviour when you use Xcode 10.

**Comment by dabaibiao** [comment]
thanks,i change provision file's bundle id end with "*" to make it support more bundle id ,so this provision can make  "com.**.xctrunner" work also.
now, WebDriverAgentRunner build successfully
but I encounter another error which is:"when I test the wad,testrunner failed, error cosole is :2020-06-10 10:54:18.508643+0800 WebDriverAgentRunner-Runner[318:7333] Running tests...
objc[318]: Class GCDAsyncSocketPreBuffer is implemented in both /private/var/containers/Bundle/Application/C78B881F-EC78-4616-840D-AA64E65960F9/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x106e19620) and /private/var/containers/Bundle/Application/C78B881F-EC78-4616-840D-AA64E65960F9/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x106d7c578). One of the two will be used. Which one is undefined.
objc[318]: Class GCDAsyncReadPacket is implemented in both /private/var/containers/Bundle/Application/C78B881F-EC78-4616-840D-AA64E65960F9/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x106e19670) and /private/var/containers/Bundle/Application/C78B881F-EC78-4616-840D-AA64E65960F9/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x106d7c5c8). One of the two will be used. Which one is undefined.
objc[318]: Class GCDAsyncWritePacket is implemented in both /private/var/containers/Bundle/Application/C78B881F-EC78-4616-840D-AA64E65960F9/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x106e196c0) and /private/var/containers/Bundle/Application/C78B881F-EC78-4616-840D-AA64E65960F9/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x106d7c618). One of the two will be used. Which one is undefined.
objc[318]: Class GCDAsyncSpecialPacket is implemented in both /private/var/containers/Bundle/Application/C78B881F-EC78-4616-840D-AA64E65960F9/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x106e19710) and /private/var/containers/Bundle/Application/C78B881F-EC78-4616-840D-AA64E65960F9/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x106d7c668). One of the two will be used. Which one is undefined.
objc[318]: Class GCDAsyncSocket is implemented in both /private/var/containers/Bundle/Application/C78B881F-EC78-4616-840D-AA64E65960F9/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x106e19760) and /private/var/containers/Bundle/Application/C78B881F-EC78-4616-840D-AA64E65960F9/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x106d7c6b8). One of the two will be used. Which one is undefined.
Test Suite 'All tests' started at 2020-06-10 10:54:21.227
Test Suite 'WebDriverAgentRunner.xctest' started at 2020-06-10 10:54:21.228
Test Suite 'UITestingUITests' started at 2020-06-10 10:54:21.228
2020-06-10 10:54:21.381144+0800 WebDriverAgentRunner-Runner[318:7333] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2020-06-10 10:54:21.410233+0800 WebDriverAgentRunner-Runner[318:7512] [MC] Invalidating cache
2020-06-10 10:54:21.416297+0800 WebDriverAgentRunner-Runner[318:7333] [MC] Reading from public effective user settings.
2020-06-10 10:54:21.503098+0800 WebDriverAgentRunner-Runner[318:7333] [User Defaults] Couldn't write value for key KeyboardAutocorrection in CFPrefsPlistSource<0x28132c980> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2020-06-10 10:54:21.550811+0800 WebDriverAgentRunner-Runner[318:7511] [MC] Invalidating cache
2020-06-10 10:54:21.553562+0800 WebDriverAgentRunner-Runner[318:7333] [MC] Reading from public effective user settings.
2020-06-10 10:54:21.556933+0800 WebDriverAgentRunner-Runner[318:7333] [User Defaults] Couldn't write value for key KeyboardPrediction in CFPrefsPlistSource<0x28132c980> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2020-06-10 10:54:21.559535+0800 WebDriverAgentRunner-Runner[318:7333] [User Defaults] Couldn't write value for key KeyboardShowPredictionBar in CFPrefsPlistSource<0x28132c980> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2020-06-10 10:54:21.566008+0800 WebDriverAgentRunner-Runner[318:7333] [User Defaults] Couldn't write value for key DidShowGestureKeyboardIntroduction in CFPrefsPlistSource<0x28132c980> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s Start Test at 2020-06-10 10:54:21.567
    t =     0.00s Set Up
2020-06-10 10:54:21.569068+0800 WebDriverAgentRunner-Runner[318:7333] -[UITestingUITests internalImplementation]: unrecognized selector sent to instance 0x280208c30
    t =     0.06s     Assertion Failure: <unknown>:0: failed: caught "NSInvalidArgumentException", "-[UITestingUITests internalImplementation]: unrecognized selector sent to instance 0x280208c30"
(
 0   CoreFoundation                      0x0000000181cc1294 <redacted> + 252
 1   libobjc.A.dylib                     0x0000000180e9b9f8 objc_exception_throw + 56
 2   CoreFoundation                      0x0000000181bddab8 <redacted> + 0
 3   CoreFoundation                      0x0000000181cc6ac4 <redacted> + 1408
 4   CoreFoundation                      0x0000000181cc875c _CF_forwarding_prep_0 + 92
 5   WebDriverAgentLib                   0x0000000106c7097c -[FBFailureProofTestCase setUp] + 136
 6   XCTest                              0x000000010305ac88 __48-[XCTestCase _performSetUpSequenceWithSelector:]_block_invoke_2 + 492
 7   XCTest                              0x00000001030b00d8 +[XCTestCase(Failures) performFailableBlock:testCase:testCaseRun:shouldInterruptTest:] + 84
 8   XCTest                              0x00000001030affdc -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 132
 9   XCTest                              0x000000010305aa7c __48-[XCTestCase _performSetUpSequenceWithSelector:]_block_invoke + 116
 10  XCTest                              0x00000001030c1d7c -[XCTContext _runActivityNamed:type:block:] + 248
 11  XCTest                              0x0000000103063480 -[XCTestCase startActivityWithTitle:type:block:] + 200
 12  XCTest                              0x0000000103063630 -[XCTestCase startActivityWithTitle:block:] + 72
 13  XCTest                              0x000000010305a9f8 -[XCTestCase _performSetUpSequenceWithSelector:] + 108
 14  XCTest                              0x0000000103058d68 -[XCTestCase invokeTest] + 728
 15  XCTest                              0x000000010305a8b8 __26-[XCTestCase performTest:]_block_invoke_2 + 44
 16  XCTest                              0x00000001030b00d8 +[XCTestCase(Failures) performFailableBlock:testCase:testCaseRun:shouldInterruptTest:] + 84
 17  XCTest                              0x00000001030affdc -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 132
 18  XCTest                              0x000000010305a7f0 __26-[XCTestCase performTest:]_block_invoke.366 + 96
 19  XCTest                              0x00000001030c248c +[XCTContext runInContextForTestCase:block:] + 212
 20  XCTest                              0x000000010305a0dc -[XCTestCase performTest:] + 540
 21  XCTest                              0x000000010309d86c -[XCTest runTest] + 60
 22  XCTest                              0x00000001030545c8 __27-[XCTestSuite performTest:]_block_invoke + 268
 23  XCTest                              0x0000000103053e58 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40
 24  XCTest                              0x00000001030c248c +[XCTContext runInContextForTestCase:block:] + 212
 25  XCTest                              0x0000000103053e00 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 156
 26  XCTest                              0x0000000103054150 -[XCTestSuite performTest:] + 320
 27  XCTest                              0x000000010309d86c -[XCTest runTest] + 60
 28  XCTest                              0x00000001030545c8 __27-[XCTestSuite performTest:]_block_invoke + 268
 29  XCTest                              0x0000000103053e58 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40
 30  XCTest                              0x00000001030c248c +[XCTContext runInContextForTestCase:block:] + 212
 31  XCTest                              0x0000000103053e00 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 156
 32  XCTest                              0x0000000103054150 -[XCTestSuite performTest:] + 320
 33  XCTest                              0x000000010309d86c -[XCTest runTest] + 60
 34  XCTest                              0x00000001030545c8 __27-[XCTestSuite performTest:]_block_invoke + 268
 35  XCTest                              0x0000000103053e58 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40
 36  XCTest                              0x00000001030c248c +[XCTContext runInContextForTestCase:block:] + 212
 37  XCTest                              0x0000000103053e00 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 156
 38  XCTest                              0x0000000103054150 -[XCTestSuite performTest:] + 320
 39  XCTest                              0x000000010309d86c -[XCTest runTest] + 60
 40  XCTest                              0x00000001030d45f0 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 176
 41  XCTest                              0x00000001030d46f0 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke.100 + 108
 42  XCTest                              0x000000010306e354 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 588
 43  XCTest                              0x00000001030d4388 -[XCTTestRunSession runTestsAndReturnError:] + 592
 44  XCTest                              0x0000000103038bbc -[XCTestDriver runTestsAndReturnError:] + 428
 45  XCTest                              0x00000001030be424 _XCTestMain + 2396
 46  WebDriverAgentRunner-Runner         0x0000000102cd3818 -[_XCTRunnerAppDelegate applicationWillResignActive:] + 0
 47  WebDriverAgentRunner-Runner         0x0000000102cd3720 _XCTRunnerRunTests + 0
 48  CoreFoundation                      0x0000000181c52e68 <redacted> + 20
 49  CoreFoundation                      0x0000000181c5276c <redacted> + 272
 50  CoreFoundation                      0x0000000181c4d7d0 <redacted> + 1024
 51  CoreFoundation                      0x0000000181c4d0b0 CFRunLoopRunSpecific + 436
 52  GraphicsServices                    0x0000000183e4d79c GSEventRunModal + 104
 53  UIKitCore                           0x00000001ae5c7978 UIApplicationMain + 212
 54  WebDriverAgentRunner-Runner         0x0000000102cd39e4 main + 192
 55  libdyld.dylib                       0x00000001817128e0 <redacted> + 4
)
    t =     0.06s Tear Down
Test Case '-[UITestingUITests testRunner]' failed (0.065 seconds).
Test Suite 'UITestingUITests' failed at 2020-06-10 10:54:21.633.
  Executed 1 test, with 1 failure (1 unexpected) in 0.065 (0.405) seconds
Test Suite 'WebDriverAgentRunner.xctest' failed at 2020-06-10 10:54:21.634.
  Executed 1 test, with 1 failure (1 unexpected) in 0.065 (0.407) seconds
Test Suite 'WebDriverAgentLib.framework' started at 2020-06-10 10:54:21.636
Test Suite 'WebDriverAgentLib.framework' passed at 2020-06-10 10:54:21.637.
  Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.001) seconds
Test Suite 'All tests' failed at 2020-06-10 10:54:21.638.
  Executed 1 test, with 1 failure (1 unexpected) in 0.065 (0.411) seconds"

this error solved too ,reference ：https://www.jianshu.com/p/fda694c2dfb3
at last ,wad is already worked on real device(12.3.1 ) 
show this to help more people.
thanks again!
