### ISSUE TITLE
Memory leak in HTTP connection handling

### ISSUE THREAD

**Issue by qmfrederik** [appium/WebDriverAgent#345]
There appears to be a memory leak in the way the WebDriverAgent handles HTTP connections.

To reproduce:
- Start WebDriverAgent using Xcode (I tested on a physical device)
- Set up port forwarding - e.g. `iproxy 8100 8100`
- Run the following script: `while true; do curl -X GET http://localhost:8100/health; done`
- Watch memory usage going up, until the process eventually runs out of memory and gets killed

This also reproduces with an route which is not handled (e.g. http://localhost:8100/not_handled)

In my environment (on an iPod running iOS 13.5), this leaks approx. 7 MB/min.

<img width="979" alt="Screenshot 2020-06-09 at 16 33 26" src="https://user-images.githubusercontent.com/9918129/84160984-0fb78a80-aa6f-11ea-8266-6a321105e6fb.png">

**Comment by qmfrederik** [comment]
The Debug Memory Graph raises warnings about 6 leaked types, of which `OS_dispatch_queue_serial` and `OS_dispatch_source` seem to be the most interesting. Printing their description yields:

```
Printing description of $7:
<OS_dispatch_source:
source[0x281400180] = 
{ 
  xref = 1,
  ref = 1,
  target = GCDAsyncSocket[0x28143c580],
  ident = 0xffffffff,
  mask = 0x0,
  pending_data = 0x0,
  registered = 0,
  armed = 0,
  cancelled,
  deleted,
  timer = { target = 0x6963374e1c, deadline = 0x6963374e1c, interval = 0x7fffffffffffffff, flags = 0x0 },
  kevent = 0x281400100,
  filter = timer
}>
```

**Comment by mykola-mokhnach** [comment]
This is our fork of RoutingHTTPServer lib: https://github.com/appium/RoutingHTTPServer. Feel free to debug it and propose your fixes.

**Comment by mykola-mokhnach** [comment]
This also might be related to https://github.com/appium/appium/issues/14416, which was fixed also on the client side in appium@beta. Worth checking anyway

**Comment by qmfrederik** [comment]
Thanks, I had a look at appium/appium#14416, it seems unrelated at first sight.

I can reproduce the issue by simply initiating a TCP connection (e.g. `echo exit | telnet localhost 8100`). Doing this in a loop leaks memory in the WDA process. This test never establishes a valid HTTP connection, so much of the middleware of RoutingHttpServer is never invoked.

It makes me think the issue is rather at the CocoaHTTPServer (also forked by appium) or at the GCDAsyncSocket level. For example, [the CocoaAsyncSocket source files](https://github.com/appium/CocoaHTTPServer/tree/master/Vendor/CocoaAsyncSocket/) used by CocaoHTTPServer haven't been updated in 7 years.

I'll have a look and let you know what I find. On the other hand, can you reproduce this problem on your machine? Would be good to know I'm not the only one seeing this :).

**Comment by mykola-mokhnach** [comment]
Closed as fixed

**Comment by nanoscopic** [comment]
In what way is this fixed? I continue to see related issues with the HTTP server used.

**Comment by qmfrederik** [comment]
I could no longer reproduce the issue described in this ticket after #348 and #349 got merged.

Are you seeing you still see this issue (memory leak by just running `echo exit | telnet localhost 8100` or `curl -X GET http://localhost:8100/health` in a loop)?

**Comment by nanoscopic** [comment]
As shared in other thread, the built in HTTP server is 1.x only, and requires Keep-Alive header as a result to re-use connections. This resolves the issue I was seeing.
