### ISSUE TITLE
Remove the 'fork' relationship with FB/WDA so this repo becomes searchable

### ISSUE THREAD

**Issue by qmfrederik** [appium/WebDriverAgent#346]
This repo is marked as forked from `facebookarchive/WebDriverAgent`, and forked repositories are not searchable in GitHub.

Could you remove the fork relationship with the upstream repository (you should be able to raise a support ticket with GitHub, and they'll take care of this)? This would have the benefit of making the code in this repository searchable.

**Comment by KazuCocoa** [comment]
> you should be able to raise a support ticket with GitHub, and they'll take care of this

Ah, okay. I haven't done this, but let us try it

**Comment by KazuCocoa** [comment]
I'm asking this for the support team

**Comment by KazuCocoa** [comment]
https://github.com/appium/WebDriverAgent is searchable by GitHub support team. Awesome
