### ISSUE TITLE
sessionId is null when visit 'http://localhost:8200/status'

### ISSUE THREAD

**Issue by 201905270246** [appium/WebDriverAgent#353]
![企业微信截图_277d2bfd-3049-408d-813e-332734ff6f47](https://user-images.githubusercontent.com/51073321/85276645-c0cd1480-b4b4-11ea-8c25-783d90fc6ca4.png)
**Warning:**

These issues are not tracked. Please create new issues in the main Appium
repository: https://github.com/appium/appium/issues/new

**Comment by electricbubble** [comment]
First, the initial value of `sessionId` is `null` because of the https://github.com/appium/WebDriverAgent/pull/324

Second, you only need to perform a `POST` request first

```
--> POST http://localhost:8100/session
{"capabilities":{}}
```

Then `http://localhost:8100/status` can have the correct `sessionId`

**Comment by KazuCocoa** [comment]
Thanks for your help @electricbubble 

The current behaviour is expected for Appium

**Comment by maulidian** [comment]
@electricbubble @KazuCocoa 
I just installed the WDA and get same problem, session ID is null.
mac os: 10.15.6
xcode: 11.6
wda: 2.20.8
any sugestion?
![image](https://user-images.githubusercontent.com/12151087/93433064-8676e600-f8f0-11ea-99c1-32599f381c51.png)

**Comment by remysabliet** [comment]
This answer is not valid anymore.
Now a request to use would be rather:

`curl -X POST -d "{\"desiredCapabilities\":{\"bundleId\":\"com.apple.mobilesafari\"}, \"capabilities\":{}}" $DEVICE_URL/session`
