### ISSUE TITLE
MJPEG server always return screenshot even screen does not change

### ISSUE THREAD

**Issue by coinhu1995** [appium/WebDriverAgent#360]
Now that the MJPEG server always returns screenshots even the screen doesn't has any change, performance may improve if it only returns frames when the screen has changed.

**Comment by mykola-mokhnach** [comment]
Do you know any way to know the screen has changed in XCTest? Normally the system itself would provide you with a callback about screen content changes to make such strategy possible. Although, in case with "active" listener, like we do now, there is no way for WDA to understand that the screen content is changed until we actually request a new screenshot and compare it with the previous one (which would make the algorithm even less performant)
