### ISSUE TITLE
Does Appium WebDriverAgent support start and stop recording for ios 13.5.1 devices  ? 

### ISSUE THREAD

**Issue by ranchor** [appium/WebDriverAgent#363]
**Warning:**
Does Appium WebDriverAgent support start and stop recording for ios 13.5.1 devices ?
These issues are not tracked. Please create new issues in the main Appium
repository: https://github.com/appium/appium/issues/new

**Comment by KazuCocoa** [comment]
Yes https://github.com/appium/appium-xcuitest-driver/blob/fd70a4fd919185e6d5fa17fc9bd34cda2a0994b2/lib/commands/recordscreen.js#L213-L356

Please consider asking questions in https://discuss.appium.io/
