### ISSUE TITLE
inspector is missing

### ISSUE THREAD

**Issue by dzl84** [appium/WebDriverAgent#367]
I started to test iOS app on an iphone. Everything went well until I visit /inspector. 

Here is what I get 
{
  "value" : {
    "error" : "unknown command",
    "message" : "Unhandled endpoint: \/inspector -- http:\/\/10.224.161.104:8100\/ with parameters {\n    wildcards =     (\n        inspector\n    );\n}",
    "traceback" : ""
  },
  "sessionId" : "A8D5E1B5-D9CF-4D35-9758-6226A94AA8DF"
}

It looks like inspector is not correctly installed. 

I tried rerun ./Scripts/bootstraps.sh w/o parameter but it always said 'All dependencies is up-to-date. So how can I do to get inspector installed and running?

**Comment by mykola-mokhnach** [comment]
This is expected. The built-in inspector module has been removed from the fork in favour of Appium Desktop's one
