### ISSUE TITLE
WebDriverAgent - Detect Orientation Change in MJPEG Stream on port 9100

### ISSUE THREAD

**Issue by ranchor** [appium/WebDriverAgent#368]
**Warning:**
How to detect orientation change in MJPEG stream on port 9100 ?

These issues are not tracked. Please create new issues in the main Appium
repository: https://github.com/appium/appium/issues/new

**Comment by KazuCocoa** [comment]
You can get the orientation via https://appium.io/docs/en/commands/session/orientation/get-orientation/ 
and probably you can get different width/height jpeg data then.

![image](https://user-images.githubusercontent.com/5511591/90029418-d2cd7580-dcf5-11ea-9703-28227ca01d09.png)

![image](https://user-images.githubusercontent.com/5511591/90029434-d7922980-dcf5-11ea-9ee5-82052f5a0390.png)


https://discuss.appium.io/ may help to ask such questions
