### ISSUE TITLE
ios13 device /source app resolution not same

### ISSUE THREAD

**Issue by swccc** [appium/WebDriverAgent#369]
**Warning:**

These issues are not tracked. Please create new issues in the main Appium
repository: https://github.com/appium/appium/issues/new

version : ios 13
device : iphone7

version : ios12
device : iphone7

I run touchAndHoldCoordination x=90, y=90
but play is another coordination

I see this problem
I run /source application size result (same app)

ios 13 iPhone7 device
: 320 * 568

ios 12 iPhone7 device
: 375 * 667

this problem... I wan't get same resolution

**Comment by KazuCocoa** [comment]
What the result of `description` by `mobile:source`?
https://appium.io/docs/en/commands/mobile-command/

If the differences existed in the result, it is XCTest internal issue. Only Apple can fix/tweak them.
(I assume this is XCTest side sincd iOS 13 and 12 has different element tree structure)

**Comment by KazuCocoa** [comment]
I think this is because of iOS internal so far.
