### ISSUE TITLE
How to use terminal the apps on the real device

### ISSUE THREAD

**Issue by chaooe** [appium/WebDriverAgent#374]
I am setuping the WDA on the real device. device info as below
iPhone 11, iOS: 13.5.1

I am trying to using post request to termial the apps on the device, it it failed.

Post *http://localhost:8100/session/0A7AF525-7E8B-490F-B81B-4662BBB7F1B2/wda/apps/terminate* with the body 
bundleId: com.baidu.app

**Comment by chaooe** [comment]
Can you help me what is the command line to terminate the apps like curl 
curl -X POST $JSON_HEADER -d "{\"duration\":3}" $DEVICE_URL/session/$SESSION_ID/wda/deactivateApp

**Comment by electricbubble** [comment]
```shell
curl -X POST $JSON_HEADER \
-d "{\"bundleId\":\"com.apple.Preferences\"}" \
$DEVICE_URL/session/$SESSION_ID/wda/apps/terminate
```

**Comment by chaooe** [comment]
Thanks very much, it works
