### ISSUE TITLE
iOS14 support

### ISSUE THREAD

**Issue by BrightHai** [appium/WebDriverAgent#376]
**Warning:**

iOS14 device with Xcode 12
![image](https://user-images.githubusercontent.com/11002329/91927510-44547e80-ed0c-11ea-818f-4901ebbb205b.png)

These issues are not tracked. Please create new issues in the main Appium
repository: https://github.com/appium/appium/issues/new

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/14696
