### ISSUE TITLE
'capabilities' is mandatory to create a new session

### ISSUE THREAD

**Issue by krishtoautomate** [appium/WebDriverAgent#405]
**REQUEST:**

`curl -X POST $JSON_HEADER -d "{'desiredCapabilities':{'bundleId':'com.apple.mobilesafari', 'shouldWaitForQuiescence':false}}" $DEVICE_URL/session`

**RESPONSE:** 
{
  "value" : {
    "error" : "session not created",
    "message" : "'capabilities' is mandatory to create a new session",
    "traceback" : ""
  },
  "sessionId" : null
}

**Comment by electricbubble** [comment]
The requested `HTTP` `Body` should look like this
```json
{
    "capabilities": {
        "alwaysMatch": {
            "bundleId": "com.apple.Preferences",
            "shouldWaitForQuiescence": false
        }
    }
}
```

**Comment by krishtoautomate** [comment]
Working thanks. Is their any postman scripts for all request types?

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-xcuitest-driver has capabilities and each example
