### ISSUE TITLE
server starts with New ip address for each phone when Webdriveragent is started targeting a device

### ISSUE THREAD

**Issue by krishtoautomate** [appium/WebDriverAgent#418]
ServerURLHere->http://192.168.0.71:8100<-ServerURLHere

A new Ip address is created for different phones when device is targeted.

How do I always start server with localhost/local ip-address

**Comment by electricbubble** [comment]
Maybe what you want is [iProxy](https://github.com/tcurdt/iProxy)

**Comment by krishtoautomate** [comment]
not iproxy - iproxy changes after port and ip are generated. I need to generate fixed ip always when build is executed.

**Comment by KazuCocoa** [comment]
I guess you're talking about without appium-xcuitest-driver.

The IP address itself cannot handle via WDA since it depends on iOS's WiFi preference (you set it as dynamic DHCP).
If you wanted to fix the address, probably you can set static IP via the device's WiFi setting by hand.
