### ISSUE TITLE
WDA can work  ，but  the inspector is  unknown command

### ISSUE THREAD

**Issue by FuChen1649** [appium/WebDriverAgent#423]
**Warning:**
the WDA can work ，but use the inspector  ，tell me  “unknown command”
My device type：
system：macOS Catalina 10.15.7
XCode：12.2
iphone：Iphone XS

These issues are not tracked. Please create new issues in the main Appium
repository: https://github.com/appium/appium/issues/new

**Comment by KazuCocoa** [comment]
What does your 'inspector' mean?
Appium only supports https://github.com/appium/appium-desktop as an inspector

**Comment by FuChen1649** [comment]
> What does your 'inspector' mean?
> Appium only supports https://github.com/appium/appium-desktop as an inspector
WDA 安装到真机后，默认提供8100端口对WDA的调用。我情况是这样的：WDA build成功了，真机上安装成功后，localhost：8100/status  可以拿到手机信息，但是该接口的sessionID 是Null， 然后通过localhost：8100/inspector访问的时候，它就提示不知道这个命令了。  以前这个接口是能调出手机当前的UI图和element元素信息的

**Comment by KazuCocoa** [comment]
/inspect no longer exist in this repository, unfortunately.
We have no plan to add it so far as same as other appoum drivers
