### ISSUE TITLE
Taking longer time to get response for "/session/{{SESSSION_ID}}/source" when list elements are 100 and above

### ISSUE THREAD

**Issue by krishtoautomate** [appium/WebDriverAgent#426]
Taking longer time to get response for "/session/{{SESSSION_ID}}/source" when list elements are 100 and above

Required some attribute to fetch elements that are visible in screen only

**Comment by KazuCocoa** [comment]
It is expected.
We provide `mobile:source` command https://appium.io/docs/en/commands/mobile-command/ to exclude arbitrary attributes. Please check it.

`snapshotMaxDepth` also can set the limit to get source depth.
https://appium.io/docs/en/advanced-concepts/settings/
