### ISSUE TITLE
iPhone 12 - PickerWheel throwing error - Picker wheel value has not been changed after 2 seconds timeout

### ISSUE THREAD

**Issue by krishtoautomate** [appium/WebDriverAgent#428]
PickerWheel throwing error - Picker wheel value has not been changed after 2 seconds timeout

org.openqa.selenium.InvalidElementStateException: Error Domain=com.facebook.WebDriverAgent Code=1 "Picker wheel value has not been changed after 2 seconds timeout" UserInfo={NSLocalizedDescription=Picker wheel value has not been changed after 2 seconds timeout}
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'B06SES20', ip: 'fd00:688f:2ed1:1682:28d5:74be:3f6e:aeb5%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '1.8.0_251'
Driver info: io.appium.java_client.AppiumDriver
Capabilities {autoDismissAlerts: false, automationName: XCUITest, browserName: , bundleId: ..., databaseEnabled: false, deviceName: ERROR:DeviceAutonotfound!, fullReset: false, javascriptEnabled: true, locationContextEnabled: false, locationServicesAuthorized: true, locationServicesEnabled: true, networkConnectionEnabled: false, newCommandTimeout: 120, noReset: false, platform: MAC, platformName: iOS, platformVersion: 14.2, takesScreenshot: true, udid: ..., useJSONSource: true, useNewWDA: true, waitForQuiescence: false, wdaLocalPort: 8301, wdaStartupRetries: 5, wdaStartupRetryInterval: 1000, webStorageEnabled: false}
Session ID: 2819a6b0-b500-4d27-92c3-0d3f167ba5cd

**Comment by electricbubble** [comment]
Because this feature is not native to `XCUITest`
https://github.com/appium/WebDriverAgent/blob/c7f01c839f9f1284e1319ccce096f6ac96153a40/WebDriverAgentLib/Categories/XCUIElement%2BFBPickerWheel.m#L33-L41

> `PickerWheel` changed in `iOS 14`

However, you can still use it, but the `offset` needs to be smaller

like 👇
```http
--> POST http://localhost:8100/session/$SESSION_ID/wda/pickerwheel/$ELEMENT_ID/select
{"offset":0.3,"order":"next"}
```
```http
--> POST http://localhost:8100/session/$SESSION_ID/wda/pickerwheel/$ELEMENT_ID/select
{"offset":0.2,"order":"previous"}
```

**Comment by krishtoautomate** [comment]
resolved thanks. can you add this differences in webdriveragent itself
