### ISSUE TITLE
MAC OS run ./Scripts/bootstrap.sh ERR. update err log

### ISSUE THREAD

**Issue by xitele2036** [appium/WebDriverAgent#429]
[@**Warning:**](
[2020-12-04T07_43_21_662Z-debug.log](https://github.com/appium/WebDriverAgent/files/5641359/2020-12-04T07_43_21_662Z-debug.log)
[eresolve-report.txt](https://github.com/appium/WebDriverAgent/files/5641360/eresolve-report.txt)

)

These issues are not tracked. Please create new issues in the main Appium
repository: https://github.com/appium/appium/issues/new

**Comment by KazuCocoa** [comment]
Could you share the result of `./Scripts/bootstrap.sh` as you titled in this issue?
Btw, if you said https://github.com/facebookarchive/WebDriverAgent/blob/aedaeed8134399381ba95c3c9718a9d12b3b317e/Inspector/package.json , this repository no longer has it.

This repository is for appium platform.
