### ISSUE TITLE
Any plan to upgrade  IDB

### ISSUE THREAD

**Issue by Veeru5c4** [appium/WebDriverAgent#431]
Is there any plan to upgrade appium-idb instead of Appium-wda

**Comment by KazuCocoa** [comment]
No.
appium-idb and this WDA have different functionality. The idb cannot cover all of WDA, afaik.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-xcuitest-driver handles appium-idb and this WDA, so you can try to replace some commands via idb, probably. (We're welcome to review PRs implement such idea)
