### ISSUE TITLE
Failed to build WDA with Xcode 12.3 RC

### ISSUE THREAD

**Issue by KazuCocoa** [appium/WebDriverAgent#432]
https://gist.github.com/KazuCocoa/eba4032c83c8b36583d0d559f7d233f1

I confirmed this error on M1 macOS.
Xcode 12.2 has no this issue, I confirmed.

I'll check this with macOS 10.15.
We should adjust relevant project's configuration then.

```
error: Building for iOS Simulator, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
error: Building for iOS Simulator, but the embedded framework 'YYCache.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
error: Building for iOS Simulator, but the linked and embedded framework 'YYCache.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
error: Building for iOS Simulator, but the linked and embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
2020-12-11 11:15:06.273 xcodebuild[79932:564522] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphonesimulator14.3-x86_64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/kazu/GitHub/ruby_lib_core/tmp/Simulator/Build/Products/WebDriverAgentRunner_iphonesimulator14.3-x86_64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x117851da0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

For both simulators and real devices

**Comment by KazuCocoa** [comment]
This happens on macOS 10.15 as well

**Comment by mykola-mokhnach** [comment]
This was expected. We'd need to dynamically adjust https://github.com/appium/WebDriverAgent/blob/master/Scripts/carthage-wrapper.sh to select either x86_64 or arm64 arch depending on the current Mac architecture.

Also, it is necessary to dynamically adjust .xcconfig files to build arm64 for simulators on such macs as well. "Adjust" simply means to perform a sed/replace operation on the file

Unfortunately I cannot do it myself, since I don't have such machine to test on

**Comment by KazuCocoa** [comment]
Yeah, I think so. > dynamic something

https://flutter.dev/docs/development/ios-project-migration is probably a similar thing.


Xcode 12.2 had no issue on both M1 (Big Sur) mac and Intel mac (10.15.7), but Xcode 12.3 RC had in both environments.
Carthage builds itself succeeded on both (Xcode 12.2 and 12.3) env via the wrapper.

**Comment by mykola-mokhnach** [comment]
> Carthage builds itself succeeded on both (Xcode 12.2 and 12.3) env via the wrapper.

They did succeed, although I assume these frameworks were only built for x64 on arm-based OS

**Comment by KazuCocoa** [comment]
With below diff and removing tvOS and Mac stuff from Carthage directory, WDA for iOS simulator succeeded to build and run via Xcode 12.3 on Intel mac
It seems we must specify sdk target in carthage build as well.

```diff
--- a/Scripts/carthage-wrapper.sh
+++ b/Scripts/carthage-wrapper.sh
@@ -21,5 +21,6 @@ trap 'rm -f "$xcconfig"' INT TERM HUP EXIT
 # the build will fail on lipo due to duplicate architectures.
 echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
 echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig
+echo 'SUPPORTED_PLATFORMS = iphonesimulator' >> $xcconfig
```

Haven't tried, but `echo 'SUPPORTED_PLATFORMS = iphoneos' >> $xcconfig` for real devices.
`appletvos` and `appletvsimulator` for tvOS.

---

> removing tvOS and Mac stuff 

This was because `--platform iOS` argument also built tvOS and Mac when I added `SUPPORTED_PLATFORMS`.

Probably I did not know well around this point...

**Comment by KazuCocoa** [comment]
> They did succeed, although I assume these frameworks were only built for x64 on arm-based OS

Yeah, I confirmed this.
Simulators got this architectural issue on M1 macOS. Real devices had no issue. (expected)

**Comment by KazuCocoa** [comment]
Tried a bit.

`--platform iOS` seems it does not work with `SUPPORTED_PLATFORMS`. All schemes ran.
example:
`./Scripts/carthage-wrapper.sh build --platform iOS --verbose` built Mac and tvOS stuff.
https://github.com/appium/WebDriverAgent/compare/master...KazuCocoa:set-supported-platform?expand=1

Potentially, we should copy what carthage does in `build`.
But in this case, probably it is better to include libraries into this project to control build configuration only in this project...

**Comment by KazuCocoa** [comment]
Potentially https://github.com/appium/WebDriverAgent/pull/434 will fix this issue as well. Will test tomorrow

(This idea is the same as mine in the above comment, _But in this case, probably it is better to include libraries into this project to control build configuration only in this project..._, so this should work well.)

**Comment by KazuCocoa** [comment]
https://github.com/appium/WebDriverAgent/pull/434

**Comment by napsta32** [comment]
Hi @KazuCocoa 
Do you know if this fix is available in latest Appium Desktop / Appium projects? I am receiving same error message when trying iOS inspector.

```
error: Building for iOS Simulator, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
error: Building for iOS Simulator, but the embedded framework 'YYCache.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
error: Building for iOS Simulator, but the linked and embedded framework 'YYCache.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
error: Building for iOS Simulator, but the linked and embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
```

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-desktop/releases/tag/v1.20.0 and appium 1.20 have
