### ISSUE TITLE
Provisioning profile "xxx" doesn't match the entitlements file's value for the get-task-allow entitlement.

### ISSUE THREAD

**Issue by Veeru5c4** [appium/WebDriverAgent#435]
I have configured distribution provisional profile when I tried to archive It get error message 

Provisioning profile "xxxx" doesn't match the entitlements file's values for the application-identifier and get-task-allow entitlements.

Please help this issue

**Comment by KazuCocoa** [comment]
It is probably a general identifier and provisioning stuff.

http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/ or google may help.
https://www.google.com/search?sxsrf=ALeKk01WIhnBCC7NHU7o7LODAFIOKm5TBw%3A1608012142913&source=hp&ei=blHYX_6DNdTL-gT67byIDQ&q=Provisioning+profile+%22xxxx%22+doesn%27t+match+the+entitlements+file%27s+values+for+the+application-identifier+and+get-task-allow+entitlements.&oq=Provisioning+profile+%22xxxx%22+doesn%27t+match+the+entitlements+file%27s+values+for+the+application-identifier+and+get-task-allow+entitlements.&gs_lcp=CgZwc3ktYWIQA1DdB1jdB2C4CmgAcAB4AIABAIgBAJIBAJgBAKABAqABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwj-8seEqM_tAhXUpZ4KHfo2D9EQ4dUDCAk&uact=5

**Comment by pppppino** [comment]
@Veeru5c4 , Hi, I got the same issue, have you figure it out? could you kindly give me some advice
