### ISSUE TITLE
WebDriverAgentRunner can't able to archive

### ISSUE THREAD

**Issue by Veeru5c4** [appium/WebDriverAgent#437]
I have configured WebDriverAgentRunner as target in Xcode automatically manage signing can't able to archive

lexical or preprocess issue

/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentLib/Vendor/CocoaHTTPServer/HTTPServer.m:565:88: error: must specify at least one argument for '...' parameter of variadic macro [-Werror,-Wgnu-zero-variadic-macro-arguments]
  NSAssert(dispatch_get_specific(IsOnServerQueueKey) != NULL, @"Must be on serverQueue");

        ^
/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentLib/Vendor/CocoaHTTPServer/HTTPServer.m:705:86: error: must specify at least one argument for '...' parameter of variadic macro [-Werror,-Wgnu-zero-variadic-macro-arguments]
  NSAssert([NSThread currentThread] == bonjourThread, @"Executed on incorrect thread");

Showing Recent Messages
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSException.h:131:9: Macro 'NSAssert' defined here

Please help this issue

**Comment by KazuCocoa** [comment]
Could you share your environment?
Host OS, Xcode version and entire your xcodebuild log may help.

**Comment by Veeru5c4** [comment]
I am using development environment

appium : 1.19.1
Xocde : 12.1
Macos  : 10.15 catalina

**Comment by KazuCocoa** [comment]
It did not reproduce on my env (same dev env tho)
Probably dependencies had got an issue... Please try to clean them once.
It also helps to run `xcodebuild` command with the log to find the cause.

**Comment by KazuCocoa** [comment]
If this was related to https://github.com/appium/WebDriverAgent/issues/442 , the cause is probably provisioning stuff.
Please make sure your provisioning profile and bundle id you might modify in this WDA project are accurate.
