### ISSUE TITLE
WDA crashes after running for some time.

### ISSUE THREAD

**Issue by Veeru5c4** [appium/WebDriverAgent#439]
Restarting after unexpected exit, crash, or test timeout in UITestingUITests/testRunner; summary will include totals from previous launches.

Test Suite 'Selected tests' started at 2020-12-16 12:17:11.416
Test Suite 'WebDriverAgentRunner.xctest' started at 2020-12-16 12:17:11.417
Test Suite 'WebDriverAgentRunner.xctest' failed at 2020-12-16 12:17:11.418.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'WebDriverAgentLib.framework' started at 2020-12-16 12:17:11.418
Test Suite 'WebDriverAgentLib.framework' passed at 2020-12-16 12:17:11.419.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'Selected tests' failed at 2020-12-16 12:17:11.419.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.003) seconds

**Comment by KazuCocoa** [comment]
Could you attach the full log?
It would be nice to create an issue with logs with `showXcodeLog` capability in https://github.com/appium/appium

https://github.com/appium/appium-xcuitest-driver

**Comment by Veeru5c4** [comment]
appium : 1.19.1
xcode : 12.2



Restarting after unexpected exit, crash, or test timeout in UITestingUITests/testRunner; summary will include totals from previous launches.

Test Suite 'Selected tests' started at 2020-12-16 17:09:40.500
Test Suite 'WebDriverAgentRunner.xctest' started at 2020-12-16 17:09:40.502
Test Suite 'WebDriverAgentRunner.xctest' failed at 2020-12-16 17:09:40.502.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'WebDriverAgentLib.framework' started at 2020-12-16 17:09:40.503
Test Suite 'WebDriverAgentLib.framework' passed at 2020-12-16 17:09:40.503.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'Selected tests' failed at 2020-12-16 17:09:40.504.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.003) seconds
2020-12-16 17:09:40.541 xcodebuild[93010:1161315] [MT] IDETestOperationsObserverDebug: 3230.530 elapsed -- Testing started completed.
2020-12-16 17:09:40.541 xcodebuild[93010:1161315] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2020-12-16 17:09:40.541 xcodebuild[93010:1161315] [MT] IDETestOperationsObserverDebug: 3230.530 sec, +3230.530 sec -- end

Test session results, code coverage, and logs:
	/Users/x/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs/Test/Test-WebDriverAgentRunner-2020.12.16_16-15-48-+0530.xcresult

Failing tests:
	WebDriverAgentRunner:
		-[UITestingUITests testRunner]

** TEST FAILED **

Testing started on " iPad'

**Comment by Veeru5c4** [comment]
provisioningProfiles:      (
    "xxxx",
    "iOS Team Provisioning Profile: xx.xx.xxx.xctrunner"
)
		hasInternalSupport:        NO
		hasWritableSystem:         NO
		isSupportedOS:             YES
		bootArgs:                  (null)
		nextBootArgs:              (null)
		connected:                 YES
		isWirelessEnabled:         NO
		connectionType:            direct
		hostname:                  (null)
		bonjourServiceName:        98:46:0a:09:f3:ac@fe80::9a46:aff:fe09:f3ac._apple-mobdev2._tcp.local.
		activeProxiedDevice:       (null)
		} (13.1 (17A844))
2020-12-16 17:09:36.346 xcodebuild[93010:1161315] [MT] IDETestOperationsObserverDebug: (E91E9ACD-4C1B-4C0D-B53E-FA5CEB7D3A7A) Finished requesting crash reports. Continuing with testing.
2020-12-16 17:09:39.720095+0530 WebDriverAgentRunner-Runner[1430:148428] Running tests...

Restarting after unexpected exit, crash, or test timeout in UITestingUITests/testRunner; summary will include totals from previous launches.

Test Suite 'Selected tests' started at 2020-12-16 17:09:40.500
Test Suite 'WebDriverAgentRunner.xctest' started at 2020-12-16 17:09:40.502
Test Suite 'WebDriverAgentRunner.xctest' failed at 2020-12-16 17:09:40.502.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'WebDriverAgentLib.framework' started at 2020-12-16 17:09:40.503
Test Suite 'WebDriverAgentLib.framework' passed at 2020-12-16 17:09:40.503.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'Selected tests' failed at 2020-12-16 17:09:40.504.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.003) seconds
2020-12-16 17:09:40.541 xcodebuild[93010:1161315] [MT] IDETestOperationsObserverDebug: 3230.530 elapsed -- Testing started completed.
2020-12-16 17:09:40.541 xcodebuild[93010:1161315] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2020-12-16 17:09:40.541 xcodebuild[93010:1161315] [MT] IDETestOperationsObserverDebug: 3230.530 sec, +3230.530 sec -- end

Test session results, code coverage, and logs:
	/Users/x/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs/Test/Test-WebDriverAgentRunner-2020.12.16_16-15-48-+0530.xcresult

Failing tests:
	WebDriverAgentRunner:
		-[UITestingUITests testRunner]

** TEST FAILED **

Testing started on 'iPad'
