### ISSUE TITLE
WDA run ./Scripts/bootstrap.sh just show Dependencies up-to-date and nothing

### ISSUE THREAD

**Issue by huanzhijin** [appium/WebDriverAgent#440]
WDA version：f5299383
WDA run ./Scripts/bootstrap.sh just show Dependencies up-to-date and nothing.
![image](https://user-images.githubusercontent.com/15280640/102321597-dd0bc300-3fb8-11eb-8ce6-ee99df0ab904.png)

**Comment by KazuCocoa** [comment]
Are you saying current master branch?
It is expected. The script does only a few things for now since we no longer need carthage stuff. It does not take time to build something.

**Comment by huanzhijin** [comment]
master branch？ Yes.
so it's don't need to run ./Scripts/bootstrap.sh   ?

**Comment by huanzhijin** [comment]
OK, I get it,is done
