### ISSUE TITLE
I can't able to debugging WebDriverAgentRunner code in  Xcode tool

### ISSUE THREAD

**Issue by Veeru5c4** [appium/WebDriverAgent#442]
I have setup WebdriveAgent xcode and configured development environment 

I have started WDA, Appium,STF I can able to see connected devices

How to debug WebDriverAgentRunner code

Please provide steps

**Comment by KazuCocoa** [comment]
I usually launch WDA via Xcode and launch Appium with `webDriverAgentUrl` capability to connect to the WDA via Appium.
Then, you can set breakpoints etc in WDA.

**Comment by Veeru5c4** [comment]
Details

Could not launch “WebDriverAgentRunner”
Domain: IDEDebugSessionErrorDomain
Code: 3
Failure Reason: No such file or directory (/Users/xxx/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/WebDriverAgentRunner-Runner)
User Info: {
    DVTRadarComponentKey = 855031;
    RawLLDBErrorMessage = "No such file or directory (/Users/xxx/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/WebDriverAgentRunner-Runner)";
}
--


System Information

macOS Version 10.15.7 (Build 19H15)
Xcode 12.2 (17535) (Build 12B45b)
Timestamp: 2020-12-17T14:36:17+05:30



Please send me in details steps

**Comment by KazuCocoa** [comment]
I haven't seen the error core, but if it was like https://developer.apple.com/forums/thread/666097 , then probably your provisioning was wrong.
