### ISSUE TITLE
How to generate .ipa file Xcode target WebDriverAgentRunner 

### ISSUE THREAD

**Issue by Veeru5c4** [appium/WebDriverAgent#443]
Xcode : 12.2
Appium : 1.19.1
signing : Automatically signing

I have configured Automatically manage signing developer account I can able to archive WebDriverAgentRunner but when I tried to genarate ipa file It will generate .xcarchive file

Can you please provide steps generate ipa file for deployment

<img width="1290" alt="Screenshot 2020-12-18 at 10 41 50 AM" src="https://user-images.githubusercontent.com/4330132/102577341-dea2cb80-411d-11eb-90d2-7afe50889ad3.png">
<img width="328" alt="Screenshot 2020-12-18 at 10 44 08 AM" src="https://user-images.githubusercontent.com/4330132/102577401-01cd7b00-411e-11eb-9e51-406df5527072.png">

**Comment by KazuCocoa** [comment]
Probably you should use CLI like https://warchimede.github.io/2017/10/05/export-xcarchive-to-ipa-xcodebuild-xcode-9/ to generate it for XCTest. Older Xcode was able to export via GUI, but it seems recent one haven't(?)
It probably depends on Xcode versions, so it would be better to find the way in Apple's official documents or xcodebuild command help.

https://discuss.appium.io/ also might help for such questions.

**Comment by Veeru5c4** [comment]
I am using xcode 12.2
I have genarated .xcarchive when open show package and contents > products  empty is there

please provide steps for genarate ipa xcode target webdriveragentrunner

**Comment by Veeru5c4** [comment]
Can you please provide instructions on how to create WDA ipa file?

**Comment by KazuCocoa** [comment]
Then, probably it no longer xcodebuild build ipa for a test bundle.
https://fbidb.io/docs/test-execution

As https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/lib/xcodebuild.js#L182, you can build a test bundle with your provisioning profile for a real device as `xcodebuild build-for-testing`. Then, `xcodebuild test-without-building` allows you to run the test bundle on the real device. The app has `.app`.

**Comment by Veeru5c4** [comment]
where I will get .app please provide steps

**Comment by Veeru5c4** [comment]
as per your comment xcodebuild.js have ['build', 'test']  so can we modify those like add on ['build', 'test', 'archive'] 

Please suggest me

**Comment by KazuCocoa** [comment]
I'd recommend you to run `xcodebuild` by hand and track the log. Then, you can see where `.app` will be.

Xcodebuild command Appium uses is printed in the appium log, so you can find how Appium works.
(Or the link I attached in the previous comment also may help to build xcodebuild command in Appium.)

**Comment by Veeru5c4** [comment]
Thanks I can able to find .app it was working fine
