### ISSUE TITLE
building WebDriverAgentRunner  is asking for a .xctrunner bundle ID

### ISSUE THREAD

**Issue by Veeru5c4** [appium/WebDriverAgent#446]
I have updated bundle id like com.xxx.xxx.WebDriverAgentRunner and confined provisional profiles when I build app
get this error 

Provisioning profile "xxxxx" has app ID "com.xx.xxx.WebDriverAgentRunner", which does not match the bundle ID "com.xx.xxx.WebDriverAgentRunner.xctrunner".

Please help this issue

Xcode : 12.2
Appium : 1.19.1

**Comment by KazuCocoa** [comment]
It is expected. `.xctrunner` is appended by Xcode automatically since Xcode 11. They changed the naming rule.
https://github.com/appium/appium/issues/13086

Our troubleshooting addresses this point http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/#troubleshooting-ideas

**Comment by Veeru5c4** [comment]
Thanks for your answer
i have gone through above links but still face same issue

may i know exact issue
how i can resolve it please provide steps

**Comment by KazuCocoa** [comment]
Afaik, the below provisioning profile can sign it as the attached link addressed. Or `*` (wildcard) also should work.
I haven't created provisioning profiles in the recent Apple environment. Please take a looks at Apple's documentation or google Apple provisioning stuff. 

> Consider generating a provisioning profile with .xctrunner identifier if you do not want to generate a wildcard one for manual configuration. The .xctrunner config support has been added since Xcode 11. A reference
