### ISSUE TITLE
Testing failed: WebDriverAgentRunner-Runner.app (462) encountered an error (The test runner failed to initialize for UI testing. (Underlying error: Not authorized for performing UI testing actions.)) ** TEST FAILED ** 

### ISSUE THREAD

**Issue by Veeru5c4** [appium/WebDriverAgent#447]
I have configured paid account distribution credentials when I will do below command getting error in WDA log

xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=0836013e8b0dfb9e4c5598974a5d5d5e64******' test

2020-12-30 15:28:00.633 xcodebuild[18015:524902] [MT] IDETestOperationsObserverDebug: 5.236 elapsed -- Testing started completed.
2020-12-30 15:28:00.633 xcodebuild[18015:524902] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2020-12-30 15:28:00.633 xcodebuild[18015:524902] [MT] IDETestOperationsObserverDebug: 5.236 sec, +5.236 sec -- end

Test session results, code coverage, and logs:
	/Users/veeraswamygajula/Desktop/WorkSpace/Projects/mcloud-ios-master/tmp/DerivedData/f655b3fad5c2ce9b04f0f556fadf4d6f6bd872b5/Logs/Test/Test-WebDriverAgentRunner-2020.12.30_15-27-53-+0530.xcresult

Testing failed:
	WebDriverAgentRunner:
		WebDriverAgentRunner-Runner.app (1186) encountered an error (The test runner failed to initialize for UI testing. If you believe this error represents a bug, please attach the result bundle at /Users/xxx/Desktop/WorkSpace/Projects/mcloud-ios-master/tmp/DerivedData/f655b3fad5c2ce9b04f0f556fadf4d6f6bd872b5/Logs/Test/Test-WebDriverAgentRunner-2020.12.30_15-27-53-+0530.xcresult. (Underlying Error: Not authorized for performing UI testing actions.))

** TEST FAILED **

Testing started
ERROR! WDA failed on iPad in 10 seconds!

Please help this issue

**Comment by Veeru5c4** [comment]
WDA was working "automatically manage signing" but uncheck automatically manage signing configured manual signing that one distribution in-house profile getting error

is It WDA will work on distribution in-house profile?

Testing failed:
WebDriverAgentRunner:
WebDriverAgentRunner-Runner.app (1186) encountered an error (The test runner failed to initialize for UI testing. If you believe this error represents a bug, please attach the result bundle at /Users/xxx/Desktop/WorkSpace/Projects/mcloud-ios-master/tmp/DerivedData/f655b3fad5c2ce9b04f0f556fadf4d6f6bd872b5/Logs/Test/Test-WebDriverAgentRunner-2020.12.30_15-27-53-+0530.xcresult. (Underlying Error: Not authorized for performing UI testing actions.))

** TEST FAILED **

**Comment by KazuCocoa** [comment]
> Not authorized for performing UI testing actions.

I haven't tried in-house, but probably yes, according to the error message.
This limitation depends on Apple.
