### ISSUE TITLE
Safari browser link not opened

### ISSUE THREAD

**Issue by Veeru5c4** [appium/WebDriverAgent#456]
When I clicked navigation button from stf portal in iPad device has opened safari browser but corresponding link not opened
Please help this issue

Xcode : 12.2
Appium : 1.19.1

**Comment by KazuCocoa** [comment]
Could you tell us more details with log? It seems XCTest internal thing so far. (Appium cannot do anything then)

**Comment by Veeru5c4** [comment]
Please find logs

Failed to open URL http://www.google.com: Error Domain=FBSOpenApplicationServiceErrorDomain Code=1 "The request to open "com.apple.mobilesafari" failed." UserInfo={BSErrorCodeDescription=RequestDenied, NSUnderlyingError=0x283647030 {Error Domain=FBSOpenApplicationErrorDomain Code=3 "Application com.derivco.devicefarm.WebDriverAgentRunner.xctrunner is neither visible nor entitled, so may not perform un-trusted user actions." UserInfo={BSErrorCodeDescription=Security, NSLocalizedFailureReason=Application com.derivco.devicefarm.WebDriverAgentRunner.xctrunner is neither visible nor entitled, so may not perform un-trusted user actions.}}, NSLocalizedDescription=The request to open "com.apple.mobilesafari" failed., FBSOpenApplicationRequestID=0xafcb, NSLocalizedFailureReason=The request was denied by service delegate (SBMainWorkspace) for reason: Security ("Application com.derivco.devicefarm.WebDriverAgentRunner.xctrunner is neither visible nor entitled, so may not perform un-trusted user actions").}

**Comment by KazuCocoa** [comment]
> Application com.derivco.devicefarm.WebDriverAgentRunner.xctrunner is neither visible nor entitled, so may not perform un-trusted user actions.

This is by Apple system.
I'm not sure the cause, but probably signing stuff?? or you should allow provisioning profile via Settings?

Anyway, probably Appium cannot do anything for this issue itself as WDA...
