### ISSUE TITLE
./Scripts/bootstrap.sh,doesn't work

### ISSUE THREAD

**Issue by yijia0404** [appium/WebDriverAgent#459]
Fetching Inspector dependencies...
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: web-driver-inspector@1.0.0
npm ERR! Found: react@15.6.1
npm ERR! node_modules/react
npm ERR!   react@"15.6.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.7.0" from react-dom@15.7.0
npm ERR! node_modules/react-dom
npm ERR!   react-dom@"^15.6.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/10015961/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/10015961/.npm/_logs/2021-01-25T07_03_30_843Z-debug.log

**Comment by yijia0404** [comment]
m1 macbookpro

**Comment by KazuCocoa** [comment]
Our repository does not have `web-driver-inspector`. I think you're using old FB WDA.
