### ISSUE TITLE
MAC bash -x ./Scripts/bootstrap.sh  err

### ISSUE THREAD

**Issue by xitele2036** [appium/WebDriverAgent#462]
**Warning:**
jianfengfus-Mac-Pro:WebDriverAgent cherryliu$ bash -x ./Scripts/bootstrap.sh 
+ set -e
+ export PATH=/Users/cherryliu/opt/anaconda2/bin:/Users/cherryliu/opt/anaconda2/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/usr/local/bin
+ PATH=/Users/cherryliu/opt/anaconda2/bin:/Users/cherryliu/opt/anaconda2/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/usr/local/bin
+ BOLD='\033[1m'
+ [[ ! -f Scripts/bootstrap.sh ]]
+ getopts ' i d D h ' option
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -z '' ]]
+ [[ -z '' ]]
+ fetch_and_build_dependencies
+ echo -e '\033[1mFetching dependencies'
Fetching dependencies
+ assert_has_carthage
+ command -v carthage
+ cmp -s Cartfile.resolved Carthage/Cartfile.resolved
+ carthage bootstrap
*** Checking out RoutingHTTPServer at "v1.0.1"
*** xcodebuild output can be found in /var/folders/3z/yqk15wl5251gh_nq3x2ng2dc0000gp/T/carthage-xcodebuild.h54N64.log
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
+ cp Cartfile.resolved Carthage
+ build_inspector
+ echo -e '\033[1mBuilding Inspector'
Building Inspector
+ assert_has_npm
+ command -v npm
++ pwd
+ CURRENT_DIR=/Users/cherryliu/Desktop/ios-test/WebDriverAgent
+ RESOURCE_BUNDLE_DIR=/Users/cherryliu/Desktop/ios-test/WebDriverAgent/Resources/WebDriverAgent.bundle
+ INSPECTOR_DIR=/Users/cherryliu/Desktop/ios-test/WebDriverAgent/Inspector
+ echo 'Creating bundle directory...'
Creating bundle directory...
+ [[ -e /Users/cherryliu/Desktop/ios-test/WebDriverAgent/Resources/WebDriverAgent.bundle ]]
+ mkdir -p /Users/cherryliu/Desktop/ios-test/WebDriverAgent/Resources/WebDriverAgent.bundle
+ cd /Users/cherryliu/Desktop/ios-test/WebDriverAgent/Inspector
+ echo 'Fetching Inspector dependencies...'
Fetching Inspector dependencies...
+ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: web-driver-inspector@1.0.0
npm ERR! Found: react@15.6.1
npm ERR! node_modules/react
npm ERR!   react@"15.6.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.7.0" from react-dom@15.7.0
npm ERR! node_modules/react-dom
npm ERR!   react-dom@"^15.6.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/cherryliu/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cherryliu/.npm/_logs/2021-01-29T07_41_29_950Z-debug.log

These issues are not tracked. Please create new issues in the main Appium
repository: https://github.com/appium/appium/issues/new

**Comment by KazuCocoa** [comment]
Your result has `web-driver-inspector`. I guess your use Facebook's WDA.
This repository no longer has it.

**Comment by xitele2036** [comment]
Which should i use，thank you

**Comment by KazuCocoa** [comment]
Sorry, what do you mean? FB/WDA or Appium/WDA?
Then, it's up to you.

This repository is designed for Appium by forking the original  FB/WDA.

**Comment by xitele2036** [comment]
I want to build an automated test platform for ios, but it seems I cannot use FB-WDA, so which one should I use? Are there any related tutorials?

**Comment by xitele2036** [comment]
I followed this document but it seems to be unavailable
https://zhuanlan.zhihu.com/p/104508507

**Comment by KazuCocoa** [comment]
Appium/XCUITest uses this repository, so around https://appium.io/docs/en/about-appium/getting-started/ , 
 https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/  and https://appium.io/docs/en/drivers/ios-xcuitest/ may help.

When you want to dive into this repository itself, https://github.com/appium/WebDriverAgent/blob/master/lib/xcodebuild.js may help to see how to build WDA.

**Comment by xitele2036** [comment]
thank you very much
