### ISSUE TITLE
sessionId Start successful access http://127.0.0.1 : 8100 / inspector no sessionid

### ISSUE THREAD

**Issue by hanwenlu2016** [appium/WebDriverAgent#465]
xcode 12.4
macOS Catalina 10.15.7

![image](https://user-images.githubusercontent.com/38583116/106986297-07eaea00-67a6-11eb-8ab5-57674bcd96a2.png)

![image](https://user-images.githubusercontent.com/38583116/106986341-2224c800-67a6-11eb-89cc-4235e80be936.png)

This is how to solve the problem！！！！！！！！！！！

**Comment by electricbubble** [comment]
https://github.com/appium/WebDriverAgent/issues/367

https://github.com/appium/WebDriverAgent/issues/423

**Comment by KazuCocoa** [comment]
It is expected. Yea, this repository has no '/inspector'.
