### ISSUE TITLE
How do I overiride the window size of image for ScreenshotsBroadcaster

### ISSUE THREAD

**Issue by krishtoautomate** [appium/WebDriverAgent#471]
How do I override the window size of image for ScreenshotsBroadcaster so that  _{{DEVICE_URL}}/session/{{SESSSION_ID}}/window/size_ will give response of my custom window size.

**Comment by KazuCocoa** [comment]
May `mjpegScalingFactor` help?
https://github.com/appium/appium-xcuitest-driver#settings-api

So far, we only provide a few configurations which has `mjpeg` prefix.

**Comment by krishtoautomate** [comment]
Possible for post request of 
_session/{session id}/window/rect_

?

also can you please share api for mjpegScalingFactor

**Comment by krishtoautomate** [comment]
modified scalingfactor with 

**Request**
{{DEVICE_URL}}/session/{{SESSSION_ID}}/appium/settings
**body:**
 {
    "settings":{
        "mjpegScalingFactor": 60
    }
}


still my window size do not change--
**GET** : {{DEVICE_URL}}/session/{{SESSSION_ID}}/window/size

**Response:**
{
    "value": {
        "width": 390,
        "height": 844
    },
    "sessionId": "9CD01A49-59DB-4C92-B914-47E8839FFBBD"
}

**Comment by KazuCocoa** [comment]
It is configured by settings API via appium-xcuitest-driver.
http://appium.io/docs/en/advanced-concepts/settings/index.html
https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Utilities/FBSettings.m


The Windows size is by the device. The scale factor is only for mjpeg server.
It does not change the device' size by `/window/size` or relevant APIs. The API is designed to return the device's window data.

**Comment by KazuCocoa** [comment]
You could modify width/height in your code and keep it, but Appium/WDA keeps the original window size.
