### ISSUE TITLE
Landscape mode launch application(com.apple.springboard) window sizes (width and height) are getting wrong values 

### ISSUE THREAD

**Issue by Veeru5c4** [appium/WebDriverAgent#473]
Hi,
I have tested WDA code in landscape mode launch applications(com.apple.springboard) width and height are getting wrong values
appium version : 1.19.0
xcode : 12.4
iOS : 14.4
Device: ipad 7th genaration

 com.apple.springboard window sizes are
command : http://192.168.0.5:8100/session/613286B9-3FBB-49FE-AE5C-B093F3E442E9/window/size
o/p: {
"value": {
"width": 1080,
"height": 1080
},
"sessionId": "613286B9-3FBB-49FE-AE5C-B093F3E442E9"
}

why landscapde mode launch icons (com.apple.springboard) same width and height ?

After open applications in landscape mode window sizes are correct

command : http://192.168.0.5:8100/session/613286B9-3FBB-49FE-AE5C-B093F3E442E9/window/size
o/p:
{
"value": {
"width": 1080,
"height": 810
},
"sessionId": "613286B9-3FBB-49FE-AE5C-B093F3E442E9"
}

In portrait mode launch icons and after app's getting correct values

command : http://192.168.0.5:8100/session/613286B9-3FBB-49FE-AE5C-B093F3E442E9/window/size
{
"value": {
"width": 810,
"height": 1080
},
"sessionId": "613286B9-3FBB-49FE-AE5C-B093F3E442E9"
}

Can you please help this issue

**Comment by KazuCocoa** [comment]
Appium simply returns the result of https://developer.apple.com/documentation/xctest/xcuielementattributes/1500911-frame 
You can report it to Apple, but nothing can do in Appium unfortunately.
