### ISSUE TITLE
QUESTION: Is it possible to rename the WebDriverAgentRunner-Runner.app to WebDriverAgentRunner-<Custom>

### ISSUE THREAD

**Issue by bell-jamesl** [appium/WebDriverAgent#478]
@mykola-mokhnach Is it possibile to rename the WebDriverAgentRunner-Runner.app to something else?
If so, what would be the implication of such change.

Thanks, much appreciated.

**Comment by KazuCocoa** [comment]
No impact unless you change bundle id.
When you change the name, I think you handle the app outside Appium. I mean you manage the WDA app installation etc by your own. Appium just connects to the WDA with `appium:webDriverAgentUrl` capability.
https://github.com/appium/WebDriverAgent/search?q=WebDriverAgentRunner-Runner

**Comment by bell-jamesl** [comment]
@KazuCocoa  Is there a way to change the display name only? I've been trying I can't seem to be able to.

**Comment by KazuCocoa** [comment]
The product name in _Build Settings_ can change.

**Comment by bell-jamesl** [comment]
@KazuCocoa ok, I'll give that a try. Also, do you know how I can set (or if even possible) to set an icon for the WebDriverAgentRunner target. I try to change it but it doesn't appear in the simulator.
![Screen Shot 2021-03-16 at 9 43 23 AM](https://user-images.githubusercontent.com/38299343/111319350-48a71000-863c-11eb-9ded-3381c549181f.jpg)


any ideas?

**Comment by KazuCocoa** [comment]
https://github.com/appium/WebDriverAgent/pull/174 might help, but I'm afraid it is not able to because it is a test bundle.
