### ISSUE TITLE
Double tap home button to show background app

### ISSUE THREAD

**Issue by krishtoautomate** [appium/WebDriverAgent#484]
how do we simulate "Double tap home button" to show background apps?

Thanks

**Comment by mykola-mokhnach** [comment]
This is not possible with XCTest

**Comment by nanoscopic** [comment]
This is not entirely accurate on latest iOS devices. On latest iOS device you can swipe from screen bottom up 1/4 of the screen to display the same screen. ( on the devices where there is no actual home button )

Also, you can enable the assistivetouch icon. ( which can be enabled through a simulated siri call )
That overlay button can then be interacted with through synthetic mouse events to open the task switcher.
