### ISSUE TITLE
How to start Webdriveragent with idb to save build time

### ISSUE THREAD

**Issue by krishtoautomate** [appium/WebDriverAgent#489]
Original command : xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination  “platform=iOS,id=$UDID test

How do i execute Webdriveragent using fb-idb or appium-idb?

**Comment by KazuCocoa** [comment]
Below lines could be a hint.
https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/lib/webdriveragent.js#L268-L280
https://github.com/appium/appium-idb/blob/2512d4f19823ae17a54408ad9f55cea0f2f1a388/lib/tools/xctest-commands.js#L21-L34

**Comment by nanoscopic** [comment]
For real devices I would recommend one of the following to start WDA: go-ios, tidevice, or iosif
