### ISSUE TITLE
Pinch api request with xy coordinates

### ISSUE THREAD

**Issue by krishtoautomate** [appium/WebDriverAgent#490]
Can you please provide the pinch api with xy coordinates without using element id

**Comment by KazuCocoa** [comment]
Did you try out w3c actions?
https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Commands/FBTouchActionCommands.m#L28
https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentTests/IntegrationTests/FBW3CMultiTouchActionsIntegrationTests.m

We have no plan to add new custom action apis by us except for calling apple's particular methods via them.
