### ISSUE TITLE
Create session is taking time

### ISSUE THREAD

**Issue by krishtoautomate** [appium/WebDriverAgent#491]
Create session is taking more time, compared to other api calls.

var data = JSON.stringify({"capabilities":{"bundleId":"com.apple.Preferences","autoLaunch":false}});

var config = {
  method: 'post',
  url: 'http://127.0.0.1:8100/session',
  headers: { 
    'Content-Type': 'application/json'
  },
  data : data
};

is it possible to optimize it.

**Comment by KazuCocoa** [comment]
Please attach the full appium log with `appium:showIOSLog`.
They helps us the possibility of optimization. You also could try out `appium:wdaEventloopIdleDelay` and (Settings) `waitForIdleTimeout`, `customSnapshotTimeout ` and `animationCoolOffTimeout` to optimize for your environment.
https://github.com/appium/appium-xcuitest-driver

**Comment by krishtoautomate** [comment]
`/Users/krish/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2021.04.05_20-56-20--0400.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-8CFD15D8-7CBD-4DA7-A818-DDF9B530AC23/WebDriverAgentRunner-C4F74FE8-560E-4AA9-BEDA-D314EF2A4BC3/Session-WebDriverAgentRunner-2021-04-05_205621-FbkohJ.log
[WebDriverAgent] Parsed BUILD_DIR configuration value: '/Users/krish/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products'
[WebDriverAgent] Got derived data root: '/Users/krish/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp'
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[iProxy@00008101:8100] Connection was refused to port 8100
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[iProxy@00008101:8100] Connection was refused to port 8100
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"14.2","version":"14.4.1"},"ios":{"ip":"192.168.0.119"},"ready":true,"build":{"upgradedAt":"1611943673417","time":"Apr  5 2021 12:27:46","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":null}
[WebDriverAgent] WebDriverAgent information:
[WebDriverAgent] {
[WebDriverAgent]   "message": "WebDriverAgent is ready to accept commands",
[WebDriverAgent]   "state": "success",
[WebDriverAgent]   "os": {
[WebDriverAgent]     "testmanagerdVersion": 28,
[WebDriverAgent]     "name": "iOS",
[WebDriverAgent]     "sdkVersion": "14.2",
[WebDriverAgent]     "version": "14.4.1"
[WebDriverAgent]   },
[WebDriverAgent]   "ios": {
[WebDriverAgent]     "ip": "192.168.0.119"
[WebDriverAgent]   },
[WebDriverAgent]   "ready": true,
[WebDriverAgent]   "build": {
[WebDriverAgent]     "upgradedAt": "1611943673417",
[WebDriverAgent]     "time": "Apr  5 2021 12:27:46",
[WebDriverAgent]     "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
[WebDriverAgent]   }
[WebDriverAgent] }
[WebDriverAgent] WebDriverAgent successfully started after 7737ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1617670584454 (20:56:24 GMT-0400 (Eastern Daylight Time))
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"arguments":["-AppleLanguages","(en)","-NSLanguages","(en)"],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":true,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Error: timeout of 240000ms exceeded
[WD Proxy]     at createError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/axios/lib/core/createError.js:16:15)
[WD Proxy]     at RedirectableRequest.handleRequestTimeout (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/axios/lib/adapters/http.js:264:16)
[WD Proxy]     at Object.onceWrapper (events.js:291:20)
[WD Proxy]     at RedirectableRequest.emit (events.js:203:13)
[WD Proxy]     at ClientRequest.eventHandlers. (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/follow-redirects/index.js:13:24)
[WD Proxy]     at ClientRequest.emit (events.js:203:13)
[WD Proxy]     at Socket.emitRequestTimeout (_http_client.js:680:40)
[WD Proxy]     at Object.onceWrapper (events.js:291:20)
[WD Proxy]     at Socket.emit (events.js:203:13)
[WD Proxy]     at Socket._onTimeout (net.js:434:8)
[WD Proxy]     at listOnTimeout (internal/timers.js:531:17)
[WD Proxy]     at processTimers (internal/timers.js:475:7)
[XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded). Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1617670645481 (20:57:25 GMT-0400 (Eastern Daylight Time))
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"arguments":["-AppleLanguages","(en)","-NSLanguages","(en)"],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":true,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"value":{"sessionId":"7B807987-0BD6-458B-9CE6-4D4F1C986F94","capabilities":{"device":"iphone","browserName":" ","sdkVersion":"14.4.1","CFBundleIdentifier":"com.apple.springboard"}},"sessionId":"7B807987-0BD6-458B-9CE6-4D4F1C986F94"}`

**Comment by krishtoautomate** [comment]
`2021-04-05 21:15:08.057800-0400 WebDriverAgentRunner-Runner[49989:4499586] Running tests...
Test Suite 'All tests' started at 2021-04-05 21:15:08.694
Test Suite 'WebDriverAgentRunner.xctest' started at 2021-04-05 21:15:08.694
Test Suite 'UITestingUITests' started at 2021-04-05 21:15:08.694
    t =      nans Suite Set Up
2021-04-05 21:15:08.713571-0400 WebDriverAgentRunner-Runner[49989:4499586] [User Defaults] Couldn't write values for keys (
    KeyboardAutocorrection
) in CFPrefsPlistSource<0x2825eaa00> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2021-04-05 21:15:08.721014-0400 WebDriverAgentRunner-Runner[49989:4499586] [User Defaults] Couldn't write values for keys (
    KeyboardPrediction
) in CFPrefsPlistSource<0x2825eaa00> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2021-04-05 21:15:08.721469-0400 WebDriverAgentRunner-Runner[49989:4499586] [User Defaults] Couldn't write values for keys (
    KeyboardShowPredictionBar
) in CFPrefsPlistSource<0x2825eaa00> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2021-04-05 21:15:08.723299-0400 WebDriverAgentRunner-Runner[49989:4499586] [User Defaults] Couldn't write values for keys (
    DidShowGestureKeyboardIntroduction
) in CFPrefsPlistSource<0x2825eaa00> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s Start Test at 2021-04-05 21:15:08.724
    t =     0.00s Set Up
2021-04-05 21:15:08.729236-0400 WebDriverAgentRunner-Runner[49989:4499586] Built at Apr  5 2021 21:12:17
2021-04-05 21:15:08.736586-0400 WebDriverAgentRunner-Runner[49989:4499586] ServerURLHere->http://192.168.0.119:8100<-ServerURLHere
2021-04-05 21:15:08.736828-0400 WebDriverAgentRunner-Runner[49989:4499603] Using singleton test manager
2021-04-05 21:15:17.661134-0400 WebDriverAgentRunner-Runner[49989:4499586] Getting the most recent active application (out of 1 total items)
    t =     8.95s Find the Application 'com.apple.springboard'
    t =    68.96s     Requesting snapshot of accessibility hierarchy for app with pid 62`

**Comment by krishtoautomate** [comment]
New WDA execution and 1st time create session is taking time.

**Comment by KazuCocoa** [comment]
Could you share the full Appium log of https://github.com/appium/WebDriverAgent/issues/491#issuecomment-813749903? I wondered about capabilities etc as well.

> New WDA execution and 1st time create session is taking time.

So, 2nd time and after had no issue, right? Possibly something building WDA time stuff?

**Comment by krishtoautomate** [comment]
i am using Webdriveragent alone without appium.(used appium to capture all logs)

Step 1. Started WDA with command - 
  // var params = ['build-for-testing', 'test-without-building','-project',path.join(wdaPath,'WebDriverAgent.xcodeproj')
    //               ,'-scheme','WebDriverAgentRunner','-destination','id='+udid+',platform=iOS'+platform
    //               ,'-configuration','Debug','IPHONEOS_DEPLOYMENT_TARGET=10.2']

Response: ServerURLHere->http://ip-of-device:8100<-ServerURLHere


Step 2. {{DEVICE_URL}}/status 

Response: FAST response, no isssues

Step 3. {{DEVICE_URL}}/session
body: 
{
    "capabilities": {
        "bundleId": "com.apple.Preferences",
        "autoLaunch": false,
        "shouldWaitForQuiescence": false,
        "waitForIdleTimeout": 10000
    }
}
Response: Takes time(1st time), till this is loaded WDA dont give any response to any new APIs

step 4. DELETE request : {{DEVICE_URL}}/session/{{SESSSION_ID}}
Response: success and fast

Step 5: Repeat Step 2 and Step 3
Response: Fast no issues.

Not sure why Step 3 is slow on 1st time

**Comment by KazuCocoa** [comment]
Capabilities like `wdaEventloopIdleDelay` also might help.
https://github.com/appium/appium-xcuitest-driver

Could you share the ios device log?
iOS device log might have more ideas what event is happening behind the new session creation.
(Potentially this is XCTest internal thing, which only Apple can improve it)

**Comment by krishtoautomate** [comment]
i compared between different devices.

i found that iPhone 12 devices taking time to create session.

**Comment by KazuCocoa** [comment]
If it was only a particular device, then it seems only Apple can fix/improve it. I guess it is inside `launch` API by XCTest (by Apple)
