### ISSUE TITLE
How to start WDA build with existing WebDriveragentRunner?

### ISSUE THREAD

**Issue by krishtoautomate** [appium/WebDriverAgent#492]
Step. Started WDA with command -

var params = ['build-for-testing', 'test-without-building','-project',path.join(wdaPath,'WebDriverAgent.xcodeproj')
 ,'-scheme','WebDriverAgentRunner','-destination','id='+udid+',platform=iOS'+platform
,'-configuration','Debug','IPHONEOS_DEPLOYMENT_TARGET=10.2']

The above command is start wda with new build and new session

How do I build xcode build to use existing WebDriverAgentRunner?

**Comment by KazuCocoa** [comment]
What do you mean _existing_? On the device?
Probably no with vanilla xcodebuild. (I'm not sure iproxy etc)

You can skip building the project with `test-without-building` and `-derivedDataPath` or `-xctestrun` xcodebuild option. (Please read the `man xcodebuild` about the option)
https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/lib/xcodebuild.js#L182

**Comment by krishtoautomate** [comment]
https://github.com/alibaba/taobao-iphone-device

able to use existing webdriveragentrunner and it is saving lot of time and also eliminating wda install errors

**Comment by KazuCocoa** [comment]
yes, you can launch the process by using 3rd party tools like idb and it.

**Comment by krishtoautomate** [comment]
do appium has any plans to use this functionality?

**Comment by KazuCocoa** [comment]
No.
`appium:launchWithIDB` is already available as https://github.com/appium/appium-xcuitest-driver.
`appium:webDriverAgentUrl` allows you to manage WDA by yourselves, so you can handle the library outside Appium and Appium can attach to it.

Read also  https://github.com/appium/appium/issues/15063

**Comment by electricbubble** [comment]
@tulasikrishan89 
Maybe you can try this [electricbubble/gidevice-cli](https://github.com/electricbubble/gidevice-cli)

**Comment by krishtoautomate** [comment]
it ll be great if we can build ipa of webdriveragent runner

**Comment by krishtoautomate** [comment]
@electricbubble / @KazuCocoa  any idea - How to build Webdriveragent ipa?

**Comment by electricbubble** [comment]
> https://stackoverflow.com/questions/5499125/how-to-create-ipa-file-using-xcode

```bash
xcodebuild build-for-testing -workspace WebDriverAgent.xcworkspace/ -scheme WebDriverAgentRunner \
-sdk iphoneos -configuration Release -derivedDataPath /tmp/derivedDataPath
```
