### ISSUE TITLE
/wda/touch/perform takes about 9 seconds or more

### ISSUE THREAD

**Issue by candialala** [appium/WebDriverAgent#497]
Xcode12.4
iPhone17 13.5.1
Updating to the latest WDA, /wda/touch/perform takes about 9 seconds or more.
![image](https://user-images.githubusercontent.com/22468260/117260451-ad832780-ae81-11eb-9d35-2d268952beb6.png)
The test only appeared after this commit(facebookarchive@618b090).
[appium_log.txt](https://github.com/appium/WebDriverAgent/files/6432762/appium_log.txt)

**Comment by candialala** [comment]
@KazuCocoa @mykola-mokhnach Could you help to solve this issue?

**Comment by KazuCocoa** [comment]
Probably `appium:showIOSLog` and timestamp log helps more to see the cause.

You also can try out `animationCoolOffTimeout`, `waitForIdleTimeout` and `customSnapshotTimeout` https://github.com/appium/appium-xcuitest-driver

**Comment by candialala** [comment]
> Probably `appium:showIOSLog` and timestamp log helps more to see the cause.
> 
> You also can try out `animationCoolOffTimeout`, `waitForIdleTimeout` and `customSnapshotTimeout` https://github.com/appium/appium-xcuitest-driver

Thanks, animationCoolOffTimeout worked for me.
