### ISSUE TITLE
Run XCTest from app

### ISSUE THREAD

**Issue by tuannm304** [appium/WebDriverAgent#499]
Hi everybody!

I would like to run WebDriverAgentRunner as normal app without xcodebuild.

I add below code to AppDelegate.m of IntegrationApp:
_- (void)applicationDidFinishLaunching:(UIApplication *)application {
  dispatch_async(dispatch_get_main_queue(), ^{
      static int isinit = 0;
      if (isinit==0) {
        [FBDebugLogDelegateDecorator decorateXCTestLogger];
        [FBConfiguration disableRemoteQueryEvaluation];
        [FBConfiguration configureDefaultKeyboardPreferences];
        if (NSProcessInfo.processInfo.environment[@"ENABLE_AUTOMATIC_SCREENSHOTS"]) {
          [FBConfiguration enableScreenshots];
        } else {
          [FBConfiguration disableScreenshots];
        }
        NSLog(@"run webserver");
        FBWebServer *webServer = [[FBWebServer alloc] init];
        [webServer startServing];
        isinit = 1;
      }
    });
}_

However when app run (by touch on IntegrationApp on iphone5), it also return in log:
...
2021-05-07 22:40:53.132038+0700 IntegrationApp[346:43018] ServerURLHere->http://192.168.1.5:8100<-ServerURLHere
2021-05-07 22:40:53.193586+0700 IntegrationApp[346:43128] Using singleton test manager
2021-05-07 22:40:53.195041+0700 IntegrationApp[346:43128] MJPEG server cannot start because the current iOS version is not supported

It seems work correct. I access http://192.168.1.5:8100/status, the respond is good.
But when I access http://192.168.1.5:8100/source. It hangs for 1 minute and return error below:
**Unexpected failure with no current test or suite: Failed to get system application: Timed out while fetching attributes 'XC_kAXXCAttributeSystemAppApplication' for Device system-wide element.**

base on stacktrace: [XCAXClient_iOS systemApplication] seem make error.

Please help!

Thanks so much!

**Comment by KazuCocoa** [comment]
i guess Apple's security system prevents getting data outside the application under test.
It needs via `testmanagerd`. https://fbidb.io/docs/test-execution/
