### ISSUE TITLE
Double quote include "HTTPResponse.h"

### ISSUE THREAD

**Issue by TheStrivingWhite** [appium/WebDriverAgent#503]
**Warning:**
Run WebDriverAgent from app

Xcode:12.5

Error: 
1. Double-quoted include “HTTPResponse.h” in framework header,expected angle-bracketed instead

There is no solution. How can we solve it

**Comment by KazuCocoa** [comment]
As same as https://github.com/appium/appium/issues/15111 ?
Then, probably your WDA is old.
Please use the latest one.

Also, what WDA version did you use also helps to understand your situation.
