### ISSUE TITLE
cannot launch app on ios14

### ISSUE THREAD

**Issue by jeannieCJY** [appium/WebDriverAgent#504]
I have build webdriveragent in xocde12 ,http://localhost:8100/status is success, but I want to launch my app  use 
"curl -X POST $JSON_HEADER -d "{\"capabilities\":{\"bundleId\":\"com.tencent.tmgp.vgame\"}}" http://localhost:8100/session"
have failed, result is 
<img width="826" alt="企业微信截图_8098e2ec-25f7-4b93-973a-5529cc0814bd" src="https://user-images.githubusercontent.com/33413436/118772445-571cdc80-b8b6-11eb-869a-05a448468032.png">
bundleid is also wrong
how to launch app??

**Comment by jlipps** [comment]
I'm not sure what capabilities WDA expects when calling it directly. Why are you using WDA directly rather than through Appium?

**Comment by electricbubble** [comment]
```http
POST: http://localhost:8100/session/$SESSION_ID/wda/apps/launch
BODY: {"bundleId":"com.apple.Preferences"}
```

**Comment by jlipps** [comment]
thanks @electricbubble, yes it's more likely that with WDA directly you just start a session and then use `/wda/apps/launch` to launch your app?

**Comment by electricbubble** [comment]
yep

**Comment by electricbubble** [comment]
My open source project implements these functions

> Just like [appium-clients](https://github.com/appium/appium/blob/5713e4ac7368388974d2269a8c5dfa62d4f77c9d/docs/en/about-appium/appium-clients.md)

**Comment by KazuCocoa** [comment]
The capability should follow W3C spec like: `{"capabilities":{"firstMatch":[{"bundleId":"com.example.apple-samplecode.UICatalog"}],"alwaysMatch":{}}}`

https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Commands/FBCustomCommands.m#L59 this may also help to launch an app without sessions.
