### ISSUE TITLE
under the Script path is no bootstrap.sh, how can i use this project to install wda?

### ISSUE THREAD

**Issue by mohiria** [appium/WebDriverAgent#517]
this project is different to facebook webdriveragent ,such as under the "Script" path has no "bootstrap.sh" script, I do't know how to use this project

**Comment by KazuCocoa** [comment]
This project is intended to use as part of Appium. https://appium.io/docs/en/drivers/ios-xcuitest/ is the usage.

Simply you can build WebDriverAgent.xcodeproj in this repository by your Xcode or xcodebuild. You can see what xcodebuild command is called in Appium's log. https://github.com/appium/WebDriverAgent/blob/master/lib/xcodebuild.js#L178-L237 is the code.
