### ISSUE TITLE
help node ./Scripts/fetch-prebuilt-wda.js running error

### ISSUE THREAD

**Issue by gffguo** [appium/WebDriverAgent#518]
I wanted to export a WDA IPA package, but there was an error running node. / scripts / fetch-prebuild-wda.js in CREATING_BUNDLES.md
![image](https://user-images.githubusercontent.com/69896971/125260302-cb15b700-e332-11eb-8580-305f0bd4397a.png)

**Comment by KazuCocoa** [comment]
Did you run `npm install` in the project root?

**Comment by gffguo** [comment]
> Did you run `npm install` in the project root?

Thank you. There is no problem running after the execution of `npm install`，I want to get an WebDriverAgent.ipa.，Do you know how to do it
