### ISSUE TITLE
Click probability doesn't work

### ISSUE THREAD

**Issue by candialala** [appium/WebDriverAgent#521]
Version: Appium 1.21.0
Xcode: 12.5
I had a problem with clicking on the new element when the page/hover jumps. It found the element and clicked the element on the log without any problems, but clicking actually it didn't work. I think this problem exists after [self fb_waitUntilFrameIsStable] ![image](https://user-images.githubusercontent.com/22468260/127465037-53ff6191-74ce-4df1-a705-b14467337ca4.png) is removed, but it is a probabilistic occurrence. Is there a good way to stabilize the page before clicking? I don't want to do that much waiting in the script.
And it only happens in the simulator.

**Comment by KazuCocoa** [comment]
hm... May `animationCoolOffTimeout` help?

**Comment by candialala** [comment]
> hm... May `animationCoolOffTimeout` help?

No help, I set animationCoolOffTimeout to 0 or 1, it still has this problem.

**Comment by KazuCocoa** [comment]
Then, I guess nothing can help so much...

Could you report it in https://github.com/appium/appium/issues/new following the template?
If other person has good idea, perhaps they can assist.
