### ISSUE TITLE
Click alert button, it need 20s

### ISSUE THREAD

**Issue by candialala** [appium/WebDriverAgent#522]
Appium version (or git revision) that exhibits the issue: 1.21.0
Last Appium version that did not exhibit the issue (if applicable): 1.19.0
Desktop OS/version used to run Appium: Mac OS Big Sur 11.5
Mobile platform/version under test: iOS 14.5
Real device or emulator/simulator: Real device/simulator

![image](https://user-images.githubusercontent.com/22468260/127644597-01e18b40-1d78-43fc-8860-1a5f46809762.png)

The same as this issue, but it only happened on the alert's button click: #472
And waitForIdleTimeout/animationCoolOffTimeout doesn't work for me.

**Comment by candialala** [comment]
The same to this issue, but it only happened on the alert's button click: https://github.com/appium/WebDriverAgent/issues/472
And waitForIdleTimeout/animationCoolOffTimeout doesn't work for me.

**Comment by KazuCocoa** [comment]
Could you report it in https://github.com/appium/appium/issues/new following the template?
(The appium repository is our main place to handle issues)
