### ISSUE TITLE
Idea: WDA versioning and printing

### ISSUE THREAD

**Issue by jlipps** [appium/WebDriverAgent#539]
Seems like there can sometimes be issues with differences between WDA and xcuitest driver versions. What if WDA had its own version and responded with it in the new session response? That way it would show up in Appium logs so it would be easier to see if someone was actually using an older WDA than they thought?

**Comment by KazuCocoa** [comment]
I think `Bundle version` and `Bundle version string (short)` in Info.plist can be used for the usage. Then, `/status` response can have the version info.

e.g. Fastlane has the action (not necessary)
https://docs.fastlane.tools/actions/commit_version_bump/#commit_version_bump

**Comment by KazuCocoa** [comment]
mm, it looks like the above my info.plist idea does not work for XCTest scheme one.
I saw also the info.plist could be cached. So to ensure the data is fresh, I needed to clean the build env before the building.

**Comment by KazuCocoa** [comment]
So, we probably only can hardcode a version around https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBSessionCommands.m#L232-L254 every release.

e.g.
```
  NSMutableDictionary *buildInfo = [NSMutableDictionary dictionaryWithDictionary:@{
    @"time" : [self.class buildTimestamp],
    @"productBundleIdentifier" : productBundleIdentifier,
    @"version" : @"3.16.0"
  }];
```

```
{
  "value" : {
    "message" : "WebDriverAgent is ready to accept commands",
    "state" : "success",
    "os" : {
      "testmanagerdVersion" : 28,
      "name" : "iOS",
      "sdkVersion" : "15.0",
      "version" : "15.0"
    },
    "ios" : {
      "simulatorVersion" : "15.0",
      "ip" : "192.168.4.20"
    },
    "ready" : true,
    "build" : {
      "version" : "3.16.0",
      "time" : "Nov 13 2021 11:33:41",
      "productBundleIdentifier" : "com.facebook.WebDriverAgentRunner"
    }
  },
  "sessionId" : null
}
```

**Comment by nanoscopic** [comment]
The trouble is worse than you are thinking. There are significant differences in what happens in WDA depending on which Xcode version is used to build it. It is not just that there are differences as WDA itself is changed.

WDA is depending on a very outdated header dump from Xcode. That dump hasn't been updated really in years. It is incorrect in a number of cases. If you compile WDA using the latest Xcode against iOS 15 and try to use it, some things are broken internally. They are worked around in weird ways ( such as by avoiding direct element taps and instead repeatedly dumping portions of the UI to get absolute coordinates and then using synthesize... )

There are many cases written into WDA to work around the bugs as Xcode changed over time. All of that stuff, for the most part, should be deleted and corrected, but it is a very difficult task to do.

Consider, for example. all of the various "swizzling" and "respondsToSelector" code. All of that stuff would go away if the latest headers were used.

**Comment by KazuCocoa** [comment]
Is `Bundle version` also available in xctest project? (just for this issue's topic, if you know of a good way)

**Comment by KimEklund13** [comment]
Could this WDA limitation be the cause of Appium not automatically installing the WDA on a iOS 15.x simulator? I had to use a workaround with installing it manually using
`(cd /usr/loca/lib/node_modules/appium/node_modules/appium-webdriveragent && .scripts/build.sh)`

However, I get this error when running that bash script:
```
+ define_xc_macros
+ XC_MACROS='CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
+ case "$TARGET" in
+ echo 'Unknown TARGET'
Unknown TARGET
+ exit 1
```

It installs the WDA on my simulator, but that `exit 1` is still concerning. Maybe because my XCode version is 13.3.1? MacOS version 12.3.1

Should I just use a lower OS version for my simulators? Is there an elegant way to see which simulator OS's would be the most "stable" to use given the WDA limitation (depends on a very outdated header dump from Xcode).

**Comment by KazuCocoa** [comment]
I think no, but perhaps it would be nice to create a new issue in https://github.com/appium/appium
btw, I don't see such behavior. My environment (macOS 12.4) and Xcode 13.x worked with iOS 15.x simulators from xcodebuild so far.

**Comment by KazuCocoa** [comment]
Btw, the script is expected to run with `TARGET` and `SDK` environment variables, so you should run `TARGET=runner SDK=sim  ./Scripts/build.sh` at least to build a simulator module.
https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/ci-jobs/scripts/build-webdriveragent.js#L30-L32

no environment variables:
```
 $ ./Scripts/build.sh
+ define_xc_macros
+ XC_MACROS='CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
+ case "$TARGET" in
+ echo 'Unknown TARGET'
Unknown TARGET
+ exit 1
```

with environment variables and Xcode 13.4:
```
$ TARGET=runner SDK=sim  ./Scripts/build.sh
+ define_xc_macros
+ XC_MACROS='CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
+ case "$TARGET" in
+ XC_TARGET=WebDriverAgentRunner
+ case "${DEST:-}" in
+ case "$ACTION" in
+ case "$SDK" in
+ XC_SDK=iphonesimulator
+ case "${CODE_SIGN:-}" in
+ case "$ACTION" in
+ xcbuild
+ destination=
+ output_command=cat
++ which xcpretty
+ '[' /Users/kazuaki/.rbenv/shims/xcpretty ']'
+ output_command=xcpretty
+ XC_BUILD_ARGS=(-project "WebDriverAgent.xcodeproj")
+ XC_BUILD_ARGS+=(-scheme "$XC_TARGET")
+ XC_BUILD_ARGS+=(-sdk "$XC_SDK")
+ XC_BUILD_ARGS+=($XC_ACTION)
+ [[ -n '' ]]
+ [[ -n '' ]]
+ XC_BUILD_ARGS+=($XC_MACROS $EXTRA_XC_ARGS)
+ xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -sdk iphonesimulator 'CODE_SIGN_IDENTITY=""' CODE_SIGNING_REQUIRED=NO
+ xcpretty
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
...
▸ Analyzing RouteRequest.m
...
▸ Copying /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/lib/libXCTestSwiftSupport.dylib
▸ Copying /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/XCTestCore.framework
▸ Copying /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework
▸ Copying /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework
▸ Touching WebDriverAgentRunner.xctest (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
▸ Build Succeeded
+ exit 0
```
