### ISSUE TITLE
uniqueMatchingSnapshotWithError exception for large view tree hierarchies

### ISSUE THREAD

**Issue by nuvolarmobileteam** [appium/WebDriverAgent#542]
We are aware that this repo does not track the issues and we should be reporting this into the main one but we have been dealing with this problem here for quite some time now and IMO this is the place where we may find the answers.

These are the issues I'm talking about: 
* https://github.com/appium/appium/issues/10654
* https://github.com/appium/appium/issues/14825

As a brief summary, it seems that once the number of subviews reaches a certain level of depth there is an exception happening in the WDA. From my experience, the `SnapshotMaxDepth` limit is 62. Over this number we would get the following error:
```
Calling AppiumDriver.getPageSource() with args: ["8d38670a-c0ab-4afe-9e28-1e288e598195"]
[XCUITest] Executing command 'getPageSource'
[WD Proxy] Matched '/source' to command name 'getPageSource'
[WD Proxy] Proxying [GET /source] to [GET http://127.0.0.1:8100/session/F03F29F0-03C9-4712-906D-1D3BBF17F114/source] with no body
[WD Proxy] Got response with status 404: {"value":{"error":"stale element reference","message":"The previously found element \"Application 'com.company.app'\" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: Error kAXErrorIllegalArgument getting snapshot for element  {pid=83633} {uid=[ID:1 hash:0x0]}","traceback":"(\n\t0   CoreFoundation                      0x0000000101ecdfba __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x0000000101d77ff5 objc_exception_throw + 48\n\t2   WebDriverAgentLib                   0x0000000127f48e45 -[XCUIElement(FBUtilities) fb_takeSnapshot] + 1077\n\t3   WebDriverAgentLib                   0x0000000127f490fb -[XCUIElement(FBUtilities) fb_snapshotWithAttributes:maxDepth:] + 187\n\t4   WebDriverAgentLib                   0x0000000127ee66a9 +[FBXPath writeXmlWithRootElement:indexPath:elementStore:includedAttributes:writer:] + 937\n\t5   WebDriverAgentLib                   0x0000000127ee59d9 +[FBXPat...
[W3C] Matched W3C error code 'stale element reference' to StaleElementReferenceError
[MJSONWP (8d38670a)] Encountered internal error running command: StaleElementReferenceError: The previously found element "Application 'com.company.app'" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: Error kAXErrorIllegalArgument getting snapshot for element  {pid=83633} {uid=[ID:1 hash:0x0]}
[MJSONWP (8d38670a)]     at errorFromW3CJsonCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
[MJSONWP (8d38670a)]     at ProxyRequestError.getActualError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
[MJSONWP (8d38670a)]     at JWProxy.command (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:272:19)
[MJSONWP (8d38670a)]     at runMicrotasks ()
[MJSONWP (8d38670a)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[HTTP] <-- GET /wd/hub/session/8d38670a-c0ab-4afe-9e28-1e288e598195/source 500 110 ms - 390
```

We have been debugging the WDA iOS project connected to our app. When `SnapshotMaxDepth` is over `62` the driver crashes because the system returns `nil` when calling `[self uniqueMatchingSnapshotWithError:error];` from `- (XCElementSnapshot *)fb_uniqueSnapshotWithError:(NSError **)error` in `FBXCodeCompatibility.m`

I guess most of these methods are private but I was wondering if anyone would have any idea why is this happening and/or a potential workaround.

Also, the following comment in the code picked our attention:
```
FBConfiguration.m
+ (void)initialize
{
  FBSnapshotRequestParameters = [NSMutableDictionary dictionaryWithDictionary:@{
    @"maxArrayCount": @INT_MAX,
    @"maxChildren": @INT_MAX,
    FBSnapshotMaxDepthKey: @50 // should be enough for the majority of the cases. The performance is acceptable for values up to 100.
    @"traverseFromParentsToChildren": @1
  }];
}
```
FBSnapshotMaxDepthKey -> So it seems that at some point the system worked with 100 subviews, right? 

Thanks in advance

**Comment by KazuCocoa** [comment]
> We are aware that this repo does not track the issues

As this issue template warning, our main repository is https://github.com/appium/appium

>  So it seems that at some point the system worked with 100 subviews, right?

Yes. Afaik, some users set the value over 100.

> because the system returns nil when calling [self uniqueMatchingSnapshotWithError:error];

This method is by XCTest (not Appium own implementation). It looks like the XCTest framework itself has an issue in this case.

**Comment by Dan-Maor** [comment]
Please see my comment here:
https://github.com/appium/appium/issues/14825#issuecomment-960537920

**Comment by nuvolarmobileteam** [comment]
@KazuCocoa and @Dan-Maor thank you very much for your time and the answers you provided. This confirms our fears: There is no solution for this one at the time being.

I'll be submitting an issue through the Feedback Assistant, that is the only thing I can think of doing as of now.

Thx again

**Comment by arthurgeron-work** [comment]
> @KazuCocoa and @Dan-Maor thank you very much for your time and the answers you provided. This confirms our fears: There is no solution for this one at the time being.
> 
> I'll be submitting an issue through the Feedback Assistant, that is the only thing I can think of doing as of now.
> 
> Thx again

Any news on this?
