### ISSUE TITLE
How to disable XC UI Test Console Log?

### ISSUE THREAD

**Issue by felixruan** [appium/WebDriverAgent#549]
When I run WebDriverAgent, I get a lot of console logs similar to these:

---------------------
Test Suite 'All tests' started at 2021-12-28 16:06:58.042
Test Suite 'WebDriverAgentRunner.xctest' started at 2021-12-28 16:06:58.043
Test Suite 'UITestingUITests' started at 2021-12-28 16:06:58.043
    t =      nans Suite Set Up
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s Start Test at 2021-12-28 16:06:58.049
    t =     0.00s Set Up
    t =    11.09s Pressing lock button
    t =    15.56s Pressing Home button
---------------------

Is it possible to disable these logs?

**Comment by KazuCocoa** [comment]
I guess no. They are by XCTest framework.

**Comment by guanzhangrtk** [comment]
@felixruan Why would you want to disable these logs? Do you feel that it could be impacting performance or something? Thanks!
