### ISSUE TITLE
Memory leak when request window size

### ISSUE THREAD

**Issue by wangchaoHZ** [appium/WebDriverAgent#579]
when i request the window size from wda，there will be Memory leak。

I wrote a script to request window size every second。use xcode instrument to watch the Memory ，After each request, the memory increases by about 0.1M。

My test script is as follows：

while [ true ]
do
  curl http://localhost:8100/session/AECA4E04-EC74-4C64-BEBA-92286EA02128/window/size
  sleep 1
done

**Comment by KazuCocoa** [comment]
Still present? It is appreciated to report it in https://github.com/appium/appium
