### ISSUE TITLE
WebDriverAgent constantly requests password to enable UI Automation on macOS Monterey

### ISSUE THREAD

**Issue by MarcosJRuiz** [appium/WebDriverAgent#587]
I updated my machine to:

- macOS Monterey Version 12.4
- Xcode Version 13.4 (13F17a)
- appium Version 1.22.3
- iOS Version 15.4.1 (19E258) device real (iPhone 11)
- iOS Version 15.5 (19F77) device real (iPhone 11)

I executed this command on host machine which is wirelessly connected to X code.
```
$ automationmodetool enable-automationmode-without-authentication
Setting up machine to allow Automation Mode without requiring user authentication... succeeded.
$ automationmodetool
Automation Mode is disabled.
This device DOES NOT REQUIRE user authentication to enable Automation Mode.
but I still get this exception Underlying Error: Timed out while enabling automation mode.
```

My devices constantly requests password to enable UI Automation.

![ERROR](https://user-images.githubusercontent.com/56564619/172440951-5687883b-4836-4450-b89f-da8c8ead0d93.png)

**Comment by KazuCocoa** [comment]
> iPhone/iPad real devices https://github.com/appium/appium/issues/15898#issuecomment-927340411 when they start a XCTest session since iOS/iPadOS 15. Disabling passcode/touch id in the device preference allows to workaround the behaviour above.

https://github.com/appium/appium-xcuitest-driver#known-problems

It is out of Appium thing by Apple.
