### ISSUE TITLE
Hello, does the library support IOS 15.6？If it does not support 15.6, when will it be updated，thank you

### ISSUE THREAD

**Issue by yanghuan1111** [appium/WebDriverAgent#606]
Hello, does the library support IOS 15.6？ Because I downloaded the latest library and saw that it only supports 15.4 at most. If it does not support 15.6, when will it be updated

**Comment by KazuCocoa** [comment]
>  I downloaded the latest library and saw that it only supports 15.4 at most.

Where did you check?
We usually address something in https://github.com/appium/appium-xcuitest-driver So far, this works up to iOS 16 RC

**Comment by yanghuan1111** [comment]
> > I downloaded the latest library and saw that it only supports 15.4 at most.
> 
> Where did you check? We usually address something in https://github.com/appium/appium-xcuitest-driver So far, this works up to iOS 16 RC
Sorry, it should be because I haven't updated Xcode to the latest version
