### ISSUE TITLE
send key events are not async or sequence

### ISSUE THREAD

**Issue by krishtoautomate** [appium/WebDriverAgent#609]
I am trying send key events in sequence with below code and my keys are miss aligned when typing or not typed in sequence

{{DEVICE_URL}}/session/{{SESSSION_ID}}/wda/keys
{"value":["t"],"frequency":60}

{{DEVICE_URL}}/session/{{SESSSION_ID}}/wda/keys
{"value":["e"],"frequency":60}

{{DEVICE_URL}}/session/{{SESSSION_ID}}/wda/keys
{"value":["s"],"frequency":60}

{{DEVICE_URL}}/session/{{SESSSION_ID}}/wda/keys
{"value":["t"],"frequency":60}

When I send each char with 4 separate api calls, for some reason, text is not typed in sequence in the device as "test"

***same issue is happening when tried with hid commands wda/performIoHidEvent

is their any solution to make it work as per requirement?

**Comment by KazuCocoa** [comment]
Except for https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Commands/FBElementCommands.m#L503, the key type depends on Apple's API https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Utilities/FBKeyboard.m#L34

I wonder if the behavior happens in the API, then maybe we do not have a good way to guarantee the order

**Comment by krishtoautomate** [comment]
may be Queue need to implemented to make key-events async or sequence

**Comment by krishtoautomate** [comment]
fixed after changing timeout:1 in handleKeys function
