### ISSUE TITLE
Missing no session for touchActions and size

### ISSUE THREAD

**Issue by krishtoautomate** [appium/WebDriverAgent#620]
https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBTouchActionCommands.m

Hi,

I see many apis are supported withoutsession, any reason for not covering touchactions.
Is it possible to add them to withoutsession

**Comment by KazuCocoa** [comment]
We generally expect session id for Appium use-case as this forked repository (maintained by us) is for Appium. Some of them are added in the previous FB's maintained age. Feel free to create a PR (and test it)

**Comment by krishtoautomate** [comment]
is it possible to create some global way of making all apis with and without sessions by default?

**Comment by KazuCocoa** [comment]
Not sure if it could for now. If some commands want to make it available without a session, you may need to specify `.withoutSession` and make sure if the command actually can work. Potentially some commands depend on session specific info, then such global thing may break something

**Comment by krishtoautomate** [comment]
Ya tried .withoutSession for touchActions and seems to be not working.
Am i missing something?

**Comment by KazuCocoa** [comment]
`XCUIApplication ` in https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBTouchActionCommands.m#L36 this should be set properly like https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBCustomCommands.m#L160 does

**Comment by krishtoautomate** [comment]
Tried that and still not working

**Comment by krishtoautomate** [comment]
fixed for wda/touch/perform with your suggestions and still not working for 

/wda/touchAndHold
/wda/dragfromtoforduration
/window/size

**Comment by KazuCocoa** [comment]
I made a PR for the window/size.

I haven't checked actions, but potentially they may work with similar changes, or they need some additional updates. (it requires debugging).

**Comment by krishtoautomate** [comment]
working for size. thanks.

Yes, may be similar changes are required for some apis.

May be some kind of global control to manage session/.withoutsession
