### ISSUE TITLE
error build: Cannot link directly with dylib/framework

### ISSUE THREAD

**Issue by timwang-ai** [appium/WebDriverAgent#624]
**Warning:**

These issues are not tracked. Please create new issues in the main Appium
repository: https://github.com/appium/appium/issues/new

error build: Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64

**Comment by KazuCocoa** [comment]
Duplicate of https://github.com/appium/appium/issues/17174
