### ISSUE TITLE
is it possible to code sign webdriveragentrunner by enterprise dist provision?

### ISSUE THREAD

**Issue by myungkyojung** [appium/WebDriverAgent#653]
Is it possible to code sign webdriveragentrunner by enterprise distribution provision for release?
I want to distribute webdriveragent.ipa to any ios devices. (including unregisted devices)

**Comment by KazuCocoa** [comment]
Perhaps yes as https://appium.github.io/appium-xcuitest-driver/4.16/real-device-config/#build-for-generic-iostvos-devices-run-manually Maybe you should do it via codesign cli

**Comment by myungkyojung** [comment]
I did code signing webdriveragent-runner by enterprise distribution provision with no errors.

but, when i run xctest using tidevice, it failed.
ex) tidevice xctest -B my_webdriveragent-runner.xctrunner

i don't know why. let me know any solutions. plz.

**Comment by KazuCocoa** [comment]
I don't use `tidevice`. Maybe asking in the tool's place might help than here

**Comment by myungkyojung** [comment]
> I don't use `tidevice`. Maybe asking in the tool's place might help than here

thank you for your answer!

**Comment by jeniva** [comment]
> > I don't use `tidevice`. Maybe asking in the tool's place might help than here我不使用 `tidevice` 。也许在工具的地方询问可能比在这里有帮助
> 
> thank you for your answer!谢谢您的回答！



> Is it possible to code sign webdriveragentrunner by enterprise distribution provision for release?是否可以通过企业发行版对 webdriveragentrunner 进行代码签名以供发布？ I want to distribute webdriveragent.ipa to any ios devices. (including unregisted devices) 我想将 webdriveragent.ipa 分发到任何 ios 设备。 （包括未注册的设备）

Can you successfully package with thedistribution provision for release? I want to distribute webdriveragent.ipa to any ios devices. (including unregisted devices) too。but when i config the project tips this error--doesn’t match the entitlements file’s value for the get-task-allow entitlement. Can you successfully use it now？
