### ISSUE TITLE
The element/active endpoint fails for some elements

### ISSUE THREAD

**Issue by rpes** [appium/WebDriverAgent#659]
WebDriverAgent 4.10.20 running on iPhone 11 with iOS 16.1.2.

The element/active endpoint seems to fail for some components. Even though there's an active element on the screen and the soft keyboard is displayed the endpoint returns Not Found.

Steps to reproduce:
1. Start the agent on the device
2. Start Safari and open the google.com web site
3. Tap the Search field in the content (see the attached screen shot). The soft keyboard opens.
4. Send GET session/<sessionId>/element/active -> not found

Looking at the component hierarchy the element shows as "type=Other". Is this the cause?

![Google](https://user-images.githubusercontent.com/5822023/216298786-cbc9f57a-3698-4768-b39a-a35e932e96d6.png)

**Comment by KazuCocoa** [comment]
Does the element has `hasKeyboardFocus`? WDA returns the hasKeyboardFocus element as active. Potentially the element as `hasFocus` https://developer.apple.com/documentation/xctest/xcuielementattributes/1627636-hasfocus or `isSelected` https://developer.apple.com/documentation/xctest/xcuielementattributes/1500581-isselected (so far, in iPhone I saw keyboard's focus had `hasKeyboardFocus` but hasFocus and isSelect were not.

https://github.com/appium/WebDriverAgent/blob/d8f1457b591b2dd00040f8336c1a7a728af871d2/WebDriverAgentLib/Categories/XCUIApplication%2BFBHelpers.m#L205

Or if the view is WebView, it does not return the element itself.

You could try get available elements which has the hasKeyboardFocus, isSelect and hasFocus with NSPredicate if one of them returns expected one
