### ISSUE TITLE
iphone 16.2 wda exited unexpectedly

### ISSUE THREAD

**Issue by lilydarling** [appium/WebDriverAgent#670]
**Warning:**

These issues are not tracked. Please create new issues in the main Appium
repository: https://github.com/appium/appium/issues/new

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/8273691/222638411-364acb92-e1e2-41e5-8160-9af3ffb628d9.png">

**Comment by KazuCocoa** [comment]
Could you explain context more?
