### ISSUE TITLE
Cannot install to real machine

### ISSUE THREAD

**Issue by WGFcode** [appium/WebDriverAgent#672]
Running the project simply prompts you to build success. Failed to install on the phone
![41678265023_ pic](https://user-images.githubusercontent.com/15343467/223665263-05126f4c-a7b7-4e94-a0c6-8383fe5e5772.jpg)

**Comment by KazuCocoa** [comment]
Please try out  https://appium.github.io/appium-xcuitest-driver/4.19/real-device-config/
i guess signing stuff.
