### ISSUE TITLE
After taking a long screenshot and clicking for 24 to 48 hours, all methods will slow down.

### ISSUE THREAD

**Issue by gassion** [appium/WebDriverAgent#707]
After taking a long screenshot and clicking for 24 to 48 hours, the clicking speed will slow down, as will other methods such as locking and unlocking. Then, restart the webdriversagent program to restore normal. Please help troubleshoot and repair it. Thank you very much!

driver.GetScreenshot();
GET /session/:session_id/screenshot
              
TouchActions action = new TouchActions(driver);
action.Down(10, 10);
action.Move(50, 50);
action.Perform();
POST /session/:session_id/touch/down

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help with that. It would be very time-consuming scenario to let it run for so long. It might be easier if you could investigate the code yourself, make the necessary performance evaluations and tell us which exact APIs cause slowness. It might also be the case it's a valid XCTest bug, and only Apple could fix that.

**Comment by gassion** [comment]
> make the necessary performance evaluations and tell us which exact APIs cause slowness

Thank you. I'm observing to see if I can find out which specific API caused it。

**Comment by gassion** [comment]
> Unfortunately we cannot help with that. It would be very time-consuming scenario to let it run for so long. It might be easier if you could investigate the code yourself, make the necessary performance evaluations and tell us which exact APIs cause slowness. It might also be the case it's a valid XCTest bug, and only Apple could fix that.

Thank you. I'm observing to see if I can find out which specific API caused it。
