### ISSUE TITLE
Error on tap action

### ISSUE THREAD

**Issue by myungkyojung** [appium/WebDriverAgent#716]
After updating to the latest version of WDA, I am getting an error on tap action. 
Is it related to the iOS version? 

- macOS:Ventura 13.3.1
- iOS: 13.3.1
- WebDriverAgent: Lastest

*WDA log
023-05-24 16:45:17.598115+0900 WebDriverAgentRunner-Runner[358:33250] *** Assertion failure in -[XCElementSnapshot _fetchSimpleValueForKey:], XCElementSnapshot.m:1065

*JSON Response
{
    "value": {
        "error": "unknown error",
        "message": "Invalid parameter not satisfying: allAttributesForKey != nil",
        "traceback": "(\n\t0   CoreFoundation                      0x000000018d988980 DC2C95C6-B954-39E8-86A2-5E0AF8801E87 + 1255808\n\t1   libobjc.A.dylib                     0x000000018d6a1028 objc_exception_throw + 60\n\t2   CoreFoundation                      0x000000018d8854fc DC2C95C6-B954-39E8-86A2-5E0AF8801E87 + 193788\n\t3   Foundation                          0x000000018dcc6690 7A7A96AF-79E4-3DB1-8904-42E61CAE8999 + 571024\n\t4   XCTAutomationSupport                0x00000001011d7600 -[XCElementSnapshot _fetchSimpleValueForKey:] + 1168\n\t5   XCTAutomationSupport                0x00000001011d9510 -[XCElementSnapshot systemAutomationProperties] + 100\n\t6   XCUIAutomation                      0x00000001010b71c0 __137+[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:]_block_invoke.19 + 212\n\t7   XCTestCore                          0x0000000100f1ccf4 +[XCTFuture futureWithDescription:block:] + 108\n\t8   XCUIAutomation                      0x00000001010b6d80 __137+[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:]_block_invoke_2 + 240\n\t9   XCTestCore                          0x0000000100f42e08 -[XCTContext _runActivityNamed:type:block:] + 196\n\t10  XCTestCore                          0x0000000100f41d20 -[XCTContext runInternalActivityNamed:block:] + 124\n\t11  XCUIAutomation                      0x00000001010b6c40 __137+[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:]_block_invoke + 204\n\t12  XCTestCore                          0x0000000100f43344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t13  XCTestCore                          0x0000000100f43430 -[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 80\n\t14  XCUIAutomation                      0x00000001010b6a28 +[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:] + 364\n\t15  XCUIAutomation                      0x00000001010b79f4 -[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:error:] + 1044\n\t16  XCUIAutomation                      0x00000001010b7cfc __70-[XCUIElement(XCUIElementEventSynthesis) _dispatchEvent:eventBuilder:]_block_invoke + 116\n\t17  XCTestCore                          0x0000000100f42e08 -[XCTContext _runActivityNamed:type:block:] + 196\n\t18  XCTestCore                          0x0000000100f41d20 -[XCTContext runInternalActivityNamed:block:] + 124\n\t19  XCUIAutomation                      0x00000001010b7bcc -[XCUIElement(XCUIElementEventSynthesis) _dispatchEvent:eventBuilder:] + 228\n\t20  XCUIAutomation                      0x00000001010e41c0 -[XCUICoordinate(XCUICoordinateTouchEvents) tap] + 376\n\t21  WebDriverAgentLib                  
....
}

**Comment by mykola-mokhnach** [comment]
this is expected. With the recent major update we only target to support Xcode 13+/iOS 15+

Consider using older WDA version if you need to test older OS versions

**Comment by myungkyojung** [comment]
@mykola-mokhnach 
I have tested down to wda 4.10.10 and have the same issue, is the macOS/xCode or SDK version related?

macOS:Ventura 13.3.1
xCode: 14.3

**Comment by KazuCocoa** [comment]
Possible duplicate of https://github.com/appium/WebDriverAgent/issues/683 
Lower Xcode versions may help

**Comment by mike1023** [comment]
I also met this issue, you can use Xcode 13.x to build wda, and I found the API `[XCUIElement tap]` does not work in ios <= 12
