### ISSUE TITLE
Latest Webdriveragent MJPEG streaming(9100) is not working in  iOS 12.x versions

### ISSUE THREAD

**Issue by krishtoautomate** [appium/WebDriverAgent#737]
Latest Webdriveragent MJPEG streaming(9100) is not working in iOS 12.x versions.

***Tried with older version and don't see any issues.

**Comment by KazuCocoa** [comment]
As of v5.0., WDA supports only iOS 15+ https://github.com/appium/WebDriverAgent/blob/master/CHANGELOG.md#500-2023-05-14  . Some methods such as screenshot may have an issue as our code cleanup for lower versions after that.

Please use older version for older iOS versions

**Comment by krishtoautomate** [comment]
Noted. Is it possible point to which component broke this functionality in older versions.

**Comment by KazuCocoa** [comment]
probably one of https://github.com/appium/WebDriverAgent/compare/v4.15.1...v5.1.0
