### ISSUE TITLE
Applying fb_shouldWaitForQuiescence when activating the app

### ISSUE THREAD

**Issue by myungkyojung** [appium/WebDriverAgent#738]
Sometimes, when launching an app in the background (/wda/apps/launch), there are occasional response timeouts.
Upon reviewing the source code, it seems that the fb_shouldWaitForQuiescence setting is not being applied when activating the AUT. (WebDriverAgent/WebDriverAgentLib/Routing/FBSession.m, line 192).
Is this a bug or intended behavior?

**Comment by KazuCocoa** [comment]
It is maybe intentional as for `[app launch]`. If you got the behavior in the activate as well, it could have the same config for the activate as well

**Comment by KazuCocoa** [comment]
wda 5.6.0 will include the change.
The next or around xcuitest driver will have the change. Thank you
