### ISSUE TITLE
Seeking advice : Method for obtaining ViewController

### ISSUE THREAD

**Issue by mynamecool** [appium/WebDriverAgent#743]
Excuse me:
What is the method to obtain the ViewController of the current page of the running app.
Thank you.

**Comment by KazuCocoa** [comment]
ViewController itself? Appium/WDA handles element via XCTest framework, so basically what Appium/WDA can do is the same as what XCTest for UI can do. It is black box testing style, so it cannot get the ViewController itself. (correct answer...?)
