### ISSUE TITLE
Help , launch WebDriverAgent failure

### ISSUE THREAD

**Issue by yuehuaguo** [appium/WebDriverAgent#744]
WebDriverAgent server start failed: receive packet: InstallationLookupFailed% 

Please help me , Why can't this service be launched?

**Comment by KazuCocoa** [comment]
How often? Did it happen after the device reboot?

It would be helpful to attach the appium log as well. Failed to launch situation could happen as iOS internal something occasionally similar to regular applications also have via XCTest's launching app method.

**Comment by eglitise** [comment]
Closing due to no response
