### ISSUE TITLE
How to obtain a list of phone installed applications bundleid

### ISSUE THREAD

**Issue by gassion** [appium/WebDriverAgent#745]
How to obtain a list of phone installed applications bundleid .

Thank you very much!

**Comment by KazuCocoa** [comment]
Please try out https://appium.github.io/appium-xcuitest-driver/4.32/execute-methods/#mobile-listapps
It is impossible to get directly via WebDriverAgent.

**Comment by gassion** [comment]
I give it a try , thank  you  help me .
