### ISSUE TITLE
Support for HID calls similar to apple

### ISSUE THREAD

**Issue by krishtoautomate** [appium/WebDriverAgent#752]
is their anyway we can achieve ioHID calls similar to below calls:

Home usagePage:0xc usage:0x40 downEvent:1 pressCount:2 down
Home usagePage:0xc usage:0x40 downEvent:1 phase:0x4 pressCount:2 end 

I am observing some syslogs from device and found the above hid calls for launching app-switcher(iphone 8)

**Comment by KazuCocoa** [comment]
https://appium.github.io/appium-xcuitest-driver/4.34/execute-methods/#mobile-performiohidevent
https://github.com/appium/WebDriverAgent/blob/2aee273ceda6ca86fcdaa57bb3067462a79e171b/WebDriverAgentLib/Commands/FBCustomCommands.m#L62

**Comment by krishtoautomate** [comment]
Input arguments doesnt meet the criteria

**Comment by KazuCocoa** [comment]
Oh, then, it is appreciate to advice what method can be used.
Current method generated an event as: https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Routing/FBXCDeviceEvent.m#L26C59-L26C78

**Comment by krishtoautomate** [comment]
https://developer.apple.com/documentation/hiddriverkit/iohideventservice/3395539-dispatchdigitizertouchevent

**Comment by KazuCocoa** [comment]
Thanks, am not sure if `HIDDriverKit` works in iOS (not macOS), but probably could research it..?

> HIDDriverKit is available on macOS.

https://developer.apple.com/documentation/hiddriverkit
