### ISSUE TITLE
How to implement multi tap

### ISSUE THREAD

**Issue by codematrixer** [appium/WebDriverAgent#763]
How can WebDriverAgent continuously and rapidly perform screen taps? I have a requirement to continuously and rapidly tap the screen to trigger a special effects check.

**Comment by KazuCocoa** [comment]
I wonder if w3c actions can do such action:
https://github.com/appium/ruby_lib_core/blob/d58652c287457270d92b8f5a1a454e42afc85ebc/test/functional/android/webdriver/w3c_actions_test.rb#L84-L94

**Comment by KazuCocoa** [comment]
https://appium.github.io/appium-xcuitest-driver/5.0/execute-methods/ may also help
