### ISSUE TITLE
Can not pack WDA to ipa

### ISSUE THREAD

**Issue by pppppino** [appium/WebDriverAgent#767]
when I use xcodebuild to pack wda, I got an error:

/Downloads/WebDriverAgent-5.8.0/WebDriverAgent.xcodeproj: error: Provisioning profile "***" doesn't match the entitlements file's value for the get-task-allow entitlement. Profile qualification is using entitlement definitions that may be out of date. Connect to network to update. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')

what should I do for it

**Comment by KazuCocoa** [comment]
XCTest project is not available as `ipa`. You need to maintain it as `.app`.

**Comment by KazuCocoa** [comment]
Btw, technically, you can create the `ipa` by manual.

1. Create `.app`
2. Create `Payload/WDA.app` (the WDA.app is by the 1 above)
3. Zip the `Payload` as `something.ipa`
