### ISSUE TITLE
When I run WebDriverAgent using xcode connection, it works fine, but when I click on the software to run it, it crash. ios version is 17.1.2, xcode version is 15.0.1.

### ISSUE THREAD

**Issue by wcb133** [appium/WebDriverAgent#822]
When I run WebDriverAgent using xcode connection, it works fine, but when I click on the software to run it, it crash. ios version is 17.1.2, xcode version is 15.0.1.

https://github.com/appium/WebDriverAgent/assets/19531971/79b79fb4-3196-4472-8416-181819d927b6

**Comment by KazuCocoa** [comment]
Because when you click the icon, it works as no-XCTest process. WDA is designed to run as XCTest  (https://developer.apple.com/documentation/xctest)

**Comment by HaoWShi** [comment]
> When I run WebDriverAgent using xcode connection, it works fine, but when I click on the software to run it, it crash. ios version is 17.1.2, xcode version is 15.0.1.
> 
>  2_1702264370.mp4

did you achieve it? by tap icon of wda to launch it ?

**Comment by HaoWShi** [comment]
Fortunately, I found a way to launch WDA on IOS by clicking on the icon after installing WDA.
Refer to the following links:
https://blog.csdn.net/boildoctor/article/details/123588999
https://zhuanlan.zhihu.com/p/673319266

1)deploy wda to IOS by xcode, trust the phone device
2)Build wda by xcode, and remember the output path of build.
3)do
`
$ xcodebuild build-for-testing -scheme WebDriverAgentRunner -sdk iphoneos -configuration Release -derivedDataPath /tmp/derivedDataPath
$ cd /tmp/derivedDataPath
$ cd Build/Products/Release-iphoneos # path might be different

Created folder `Payload` and put `.app` into it
then compressed to zip, change extention name to `.ipa`. That's all.
$ mkdir Payload && cp -r *.app Payload
`
4) delete XC** folder in WebDriverAgentRunner-Runner.app/Frameworks
5) Reconstructing Signature Information Refer the https://blog.csdn.net/boildoctor/article/details/123588999
I use the '方法2', Finally, a message indicating that the signature is being replaced is obtained.
6) use 'zip -r WDA.ipa Payload' to deploy wda, and install WDA.ipa to iphone

After the preceding steps are performed, you can directly click the wda icon on the mobile phone to start the wda.

**Comment by KazuCocoa** [comment]
Did it work on iOS 17 as well? It works on iOS 16 and lower, but iOS 17 did not before. Lauching it as a xctest process was okay.

**Comment by HaoWShi** [comment]
Yes， I  test it on iphone15(IOS17..2) and Mac

**Comment by KazuCocoa** [comment]
Thank you, it's interesting. Then, you could use https://appium.github.io/appium-xcuitest-driver/latest/guides/run-prebuilt-wda/#download-prebuilt-wda (available https://github.com/appium/WebDriverAgent/releases) for the `.app` in your step. You only need 5 and 6. (Maybe 5 does resign)

**Comment by HaoWShi** [comment]
I'll test it next week. If it works, it'll be great.
