### ISSUE TITLE
FR: Can we use `XCUIDevice.shared.system.open(url)` to open deep links to skip Safari?

### ISSUE THREAD

**Issue by amedvedjev** [appium/WebDriverAgent#823]
While testing deep links on real devices we need to open Safari.
With iOS17 there is super fast way to use `XCUIDevice.shared.system.open(url)`

Is it possible add support it with WDA?

**Comment by KazuCocoa** [comment]
Do you mean https://github.com/search?q=repo%3Aappium%2FWebDriverAgent+openURL&type=code added since Xcode 14.3?

**Comment by amedvedjev** [comment]
wow! sorry maybe blind, what Java-client command for this?

wow! `driver.get("my_app://command")` -> works same as with Android!

**Comment by amedvedjev** [comment]
implemented
