### ISSUE TITLE
I have no issues running WDA directly through Xcode on a real device. Whether started by clicking or through Sib, it works fine. However, after packaging WDA into an IPA file, installing it via Sib, and then launching WDA, it crashes. It doesn't happen every time, but the occurrence probability is quite high.

### ISSUE THREAD

**Issue by guoxiangyang163** [appium/WebDriverAgent#829]
crash log 
[crash.txt](https://github.com/appium/WebDriverAgent/files/13724676/crash.txt)

**Comment by KazuCocoa** [comment]
Did you start the WDA process as XCTest process?
hm, no idea from the crash log. Btw, what is the Sib?

**Comment by guoxiangyang163** [comment]
The root cause of the issue has been identified. It was due to the fact that in the Scheme Build configuration, IntegrationApp was included in the packaging:
<BuildActionEntry
    buildForTesting = "YES"
    buildForRunning = "YES"
    buildForProfiling = "YES"
    buildForArchiving = "YES"
    buildForAnalyzing = "YES">
    <BuildableReference
        BuildableIdentifier = "primary"
        BlueprintIdentifier = "EE9B75D31CF7956C00275851"
        BuildableName = "IntegrationApp.app"
        BlueprintName = "IntegrationApp"
        ReferencedContainer = "container:WebDriverAgent.xcodeproj">
    </BuildableReference>
</BuildActionEntry>
This caused issues with both WDA IPA installation and startup.

**Comment by guoxiangyang163** [comment]
The root cause of the issue has been identified. It was due to the fact that in the Scheme Build configuration, IntegrationApp was included in the packaging:
`
         <BuildActionEntry
            buildForTesting = "YES"
            buildForRunning = "YES"
            buildForProfiling = "YES"
            buildForArchiving = "YES"
            buildForAnalyzing = "YES">
            <BuildableReference
               BuildableIdentifier = "primary"
               BlueprintIdentifier = "EE9B75D31CF7956C00275851"
               BuildableName = "IntegrationApp.app"
               BlueprintName = "IntegrationApp"
               ReferencedContainer = "container:WebDriverAgent.xcodeproj">
            </BuildableReference>
         </BuildActionEntry>
`
This caused issues with both WDA IPA installation and startup.
