### ISSUE TITLE
"Failed to find Matching Arch for input file"

### ISSUE THREAD

**Issue by tking16** [appium/WebDriverAgent#830]
![Screenshot 2023-12-28 at 12 38 00](https://github.com/appium/WebDriverAgent/assets/13576824/22833906-1e0e-46de-979d-b7e83f0acf5f)

Just thought I'd highlight a potential issue, on some machines I can't drag and drop the Webdriver 5.15.5 release onto the simulator

- Simulator is iOS 17.0
- The Machine is an intel Mac mini running Sonoma
- Xcode version 15.0

I've had success installing on completely different machines (can't pinpoint what makes it work as the machines can be M1 spec, or have xcode 15.1 installed instead)

**Comment by KazuCocoa** [comment]
It could depend on how you built wda.
e,g, https://github.com/appium/WebDriverAgent/blob/766be59ef31753f4029c57c7a13cc01b1312cb9e/Scripts/ci/build-real.sh#L5-L10 then the build would be for `arm64`.
Please report the main appium repository with logs/how to build the wda and xcodebuild if needed
