### ISSUE TITLE
Enterprise certificate packaging error

### ISSUE THREAD

**Issue by dusk0504** [appium/WebDriverAgent#835]
I tried that the personal certificate can package WDA correctly, but the enterprise certificate cannot be packaged normally. There will be problems in the steps related to signing. How to solve it?

**Comment by KazuCocoa** [comment]
https://discuss.appium.io/ might help to ask such a general question. The typical thing is the wrong bundle id.
https://appium.github.io/appium-xcuitest-driver/5.14/real-device-config/

**Comment by dusk0504** [comment]
> https://discuss.appium.io/ might help to ask such a general question. The typical thing is the wrong bundle id. https://appium.github.io/appium-xcuitest-driver/5.14/real-device-config/

Thanks
