### ISSUE TITLE
Can't chose simulator's XctestrunFile created by arm64 PC

### ISSUE THREAD

**Issue by suzukieita** [appium/WebDriverAgent#837]
I created an XctestrunFile with my Apple silicon PC for the simulator build, and it creates a file like this
```
WebDriverAgentRunner_iphonesimulator16.4-arm64.xctestrun
```

But I can't specify this file in the appium with `useXctestrunFile` and `bootstrapPath` capabilities.

I checked the code and I realized it is hard-coded. If the device is a simulator, it is always assumed `x86_64`. 
I think the simulator version also can have arm64 architecture.

https://github.com/appium/WebDriverAgent/blob/e011c7e83919e6982d857d384b97416a22a46350/lib/utils.js#L262-L266

**Comment by KazuCocoa** [comment]
appium-webdriveragent v5.15.8 has the fix https://github.com/appium/WebDriverAgent/pull/840
