### ISSUE TITLE
Identifier '_XCTSetApplicationStateTimeout' is reserved because it starts with '_' followed by a capital letter

### ISSUE THREAD

**Issue by whhaijun** [appium/WebDriverAgent#839]
Identifier '_XCTSetApplicationStateTimeout' is reserved because it starts with '_' followed by a capital letter

Identifier '_XCTApplicationStateTimeout' is reserved because it starts with '_' followed by a capital letter

Identifier '_XCTestCaseImplementation' is reserved because it starts with '_' followed by a capital letter

xcode 14.2

**Comment by KazuCocoa** [comment]
Could you explain further? e.g.  what source code did you build, xcodebuild command and the result as build log, etc

`_XCTestCaseImplementation` is in headers but not called by code right now. I wondered if at least you referred to not the latest code. Does it also occur with Xcode 14.3.1 without build cache? (which is the latest Xcode 14)
https://github.com/search?q=repo%3Aappium%2FWebDriverAgent+_XCTestCaseImplementation&type=code

**Comment by whhaijun** [comment]
ERROR Image

[https://upload-images.jianshu.io/upload_images/3159832-ae443abaffa37f42.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240](https://upload-images.jianshu.io/upload_images/3159832-ae443abaffa37f42.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

[https://upload-images.jianshu.io/upload_images/3159832-345ad7a4bdcee084.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240](https://upload-images.jianshu.io/upload_images/3159832-ae443abaffa37f42.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by KazuCocoa** [comment]
They returned `403 Forbidden`

**Comment by whhaijun** [comment]
So what should we do about it

**Comment by KazuCocoa** [comment]
You could upload images to GitHub directory. The given links show 403 Forbidden for me.

Basically we need:

- Error lines
    - based on GitHub repo's link is fine https://github.com/appium/WebDriverAgent
        - e.g. a link like https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBAlertViewCommands.m#L28 where you got the error
- Revision of WDA code you used


For now, our CI uses Xcode 14.2 and 15.0, but they do not have build errors; probably you reported ones.
https://github.com/appium/WebDriverAgent/blob/master/.azure-pipelines.yml


as my previous comment, you potentially used old code, then please try out with latest code.

**Comment by whhaijun** [comment]
Try again
https://github.com/whhaijun/image/blob/main/%E4%BC%81%E4%B8%9A%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_421765c9-66f7-4250-910b-5dc5176c88ad.png

https://github.com/whhaijun/image/blob/main/%E4%BC%81%E4%B8%9A%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_5ecbbeb5-5ac1-43ed-b1d2-28a6ee6ed028.png

**Comment by KazuCocoa** [comment]
Thanks. Actually they are in the WDA code, but I have yet to see the error even with Xcode 14.2 so far on my local machine and our CI (since build succeeded).

how about clearing your local build cache?

**Comment by whhaijun** [comment]
As is shown in the picture
https://github.com/whhaijun/image/blob/main/50e21a68-9d79-48bf-b853-3e4d22381b5e.png

**Comment by KazuCocoa** [comment]
yes, removing all of them is it. I have tried to reproduce that on intel/m1 mac hosts with Xcode 14.2 with macOS 12.6.5 and 13.6, but my environment was not able to reproduce the error. I cannot help further as there is no reproducible env on my side (including CI env)

**Comment by whhaijun** [comment]
Oh, thanks all the same.

**Comment by whhaijun** [comment]
Already working
