### ISSUE TITLE
Mixing declarations and code is incompatible with standards before C99

### ISSUE THREAD

**Issue by hpcll** [appium/WebDriverAgent#842]
**Warning:**

These issues are not tracked. Please create new issues in the main Appium
repository: https://github.com/appium/appium/issues/new
![image](https://github.com/appium/WebDriverAgent/assets/18572467/4de0725d-bf55-466a-8404-45d1f66bb7b8)

**Comment by KazuCocoa** [comment]
Please write down the details of the WDA version and Xcode version, etc and report it to https://github.com/appium/appium/issues/new. At least the reported line does not exist in the latest branch.
