### ISSUE TITLE
Iphone14，ios17.3，v5.15.8 Touch WebDriverAgent icon then crash。

### ISSUE THREAD

**Issue by wangyuc** [appium/WebDriverAgent#844]
crash infomation：
 "lastExceptionBacktrace" : [{"imageOffset":968312,"symbol":"__exceptionPreprocess","symbolLocation":164,"imageIndex":15},{"imageOffset":179328,"symbol":"objc_exception_throw","symbolLocation":60,"imageIndex":14},{"imageOffset":7015736,"symbol":"_userInfoForFileAndLine","symbolLocation":0,"imageIndex":21},{"imageOffset":364248,"symbol":"+[XCTRunnerDaemonSession sharedSession]","symbolLocation":316,"imageIndex":4},{"imageOffset":101864,"symbol":"-[XCUIDevice initLocalDeviceWithPlatform:]","symbolLocation":164,"imageIndex":6},{"imageOffset":101500,"symbol":"+[XCUIDevice localDevice]","symbolLocation":60,"imageIndex":6},{"imageOffset":483972,"symbol":"XCUIInitializeForUITesting","symbolLocation":424,"imageIndex":6},{"imageOffset":538116,"symbol":"-[XCTestDriver(XCTTestRunSessionUIAutomationDelegate) _preTestingInitializationForUIAutomation]","symbolLocation":40,"imageIndex":6},{"imageOffset":256340,"symbol":"-[XCTestDriver _runTests]","symbolLocation":436,"imageIndex":4},{"imageOffset":37620,"symbol":"_XCTestMain","symbolLocation":92,"imageIndex":4},{"imageOffset":37168,"symbol":"-[_XCTRunnerAppDelegate application:didFinishLaunchingWithOptions:]","symbolLocation":0,"imageIndex":9},{"imageOffset":37068,"symbol":"_XCTRunnerRunTests","symbolLocation":0,"imageIndex":9},{"imageOffset":225592,"symbol":"__CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__","symbolLocation":28,"imageIndex":15},{"imageOffset":219436,"symbol":"__CFRunLoopDoBlocks","symbolLocation":356,"imageIndex":15},{"imageOffset":210988,"symbol":"__CFRunLoopRun","symbolLocation":848,"imageIndex":15},{"imageOffset":209912,"symbol":"CFRunLoopRunSpecific","symbolLocation":608,"imageIndex":15},{"imageOffset":13560,"symbol":"GSEventRunModal","symbolLocation":164,"imageIndex":16},{"imageOffset":2279584,"symbol":"-[UIApplication _run]","symbolLocation":888,"imageIndex":17},{"imageOffset":2277084,"symbol":"UIApplicationMain","symbolLocation":340,"imageIndex":17},{"imageOffset":37776,"symbol":"main","symbolLocation":160,"imageIndex":9},{"imageOffset":24012,"symbol":"start","symbolLocation":2240,"imageIndex":18}],

**Comment by KazuCocoa** [comment]
Afaik, it is expected since the method does not start the WDA process as XCTest process. Past iOS did not behave so, but maybe the behavior started since iOS 17 (and the test-related changes). WDA is expected to start as a XCTest process.

**Comment by HaoWShi** [comment]
Fortunately, I found a way to launch WDA on IOS by clicking on the icon after installing WDA.
Refer to the following links:
https://blog.csdn.net/boildoctor/article/details/123588999
https://zhuanlan.zhihu.com/p/673319266

1)deploy wda to IOS by xcode, trust the phone device
2)Build wda by xcode, and remember the output path of build.
3)do
`
$ xcodebuild build-for-testing -scheme WebDriverAgentRunner -sdk iphoneos -configuration Release -derivedDataPath /tmp/derivedDataPath
$ cd /tmp/derivedDataPath
$ cd Build/Products/Release-iphoneos # path might be different

Created folder `Payload` and put `.app` into it
then compressed to zip, change extention name to `.ipa`. That's all.
$ mkdir Payload && cp -r *.app Payload
`
4) delete XC** folder in WebDriverAgentRunner-Runner.app/Frameworks
5) Reconstructing Signature Information Refer the https://blog.csdn.net/boildoctor/article/details/123588999
I use the '方法2', Finally, a message indicating that the signature is being replaced is obtained.
6) use 'zip -r WDA.ipa Payload' to deploy wda, and install WDA.ipa to iphone

After the preceding steps are performed, you can directly click the wda icon on the mobile phone to start the wda.

**Comment by mimibuduo123** [comment]
After restarting the phone, it ceased to function
