### ISSUE TITLE
build failure in new update 14.4

### ISSUE THREAD

**Issue by Brijeshkr565** [appium/WebDriverAgent#875]
**Warning:**

Failed to build project WebDriverAgent with scheme WebDriverAgentRunner.: Cannot test target “WebDriverAgentRunner” on “My Mac”: My Mac’s macOS 14.2.1 doesn’t match WebDriverAgentRunner’s macOS 14.4 deployment target.

**Comment by KazuCocoa** [comment]
This is for iOS/tvOS, so My Mac deployment target should not work
