### ISSUE TITLE
After installing the latest WebDriverAgent (WDA) on an iOS 17.4.1 system, the device can be tested using Xcode successfully. However, once the device is unplugged and I attempt to open WDA manually, it crashes. Has anyone experienced this problem? Assistance would be appreciated.

### ISSUE THREAD

**Issue by Jim-JimZ** [appium/WebDriverAgent#896]
[WebDriverAgentRunner-Runner-2024-04-24-164546.log](https://github.com/appium/WebDriverAgent/files/15092356/WebDriverAgentRunner-Runner-2024-04-24-164546.log)
Crash logs are attached

**Comment by KazuCocoa** [comment]
If you meant launching the app via icon, it is because of XC* in the embedded frameworks. https://appium.github.io/appium-xcuitest-driver/latest/guides/run-preinstalled-wda/#additional-requirement-for-ios-17tvos17 would help then.

**Comment by Jim-JimZ** [comment]
> If you meant launching the app via icon, it is because of XC* in the embedded frameworks. https://appium.github.io/appium-xcuitest-driver/latest/guides/run-preinstalled-wda/#additional-requirement-for-ios-17tvos17 would help then.

I followed the method described in the link above to delete "XC*.framework" from the WebDriverAgentRunner-Runner.app/Frameworks/ directory, but the program still crashes. Is there any other way to solve this? I have attached the crash log.

**Comment by Jim-JimZ** [comment]
[WebDriverAgentRunner-Runner-2024-05-07-113629.log](https://github.com/appium/WebDriverAgent/files/15270314/WebDriverAgentRunner-Runner-2024-05-07-113629.log)

**Comment by KazuCocoa** [comment]
I haven't seen this behavior. but on the device, it did not have `XCTest.framework`. Usually a device has `/System/Developer/Library/Frameworks/XCTest.framework` but it looks like not on the device.

Is the device developer mode enabled? https://appium.github.io/appium-xcuitest-driver/latest/preparation/real-device-config/

>   "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/XCTest.framework\/XCTest","Referenced from: <A07B2436-72C9-3BF4-901B-761A0341DC66> \/Volumes\/VOLUME\/*\/WebDriverAgentRunner-Runner.app\/WebDriverAgentRunner-Runner","Reason: tried: '\/private\/var\/containers\/Bundle\/Application\/67AA629B-54DF-4FB3-9676-B7DF6020489F\/WebDriverAgentRunner-Runner.app\/Frameworks\/XCTest.framework\/XCTest' (no such file), '\/System\/Developer\/Library\/Frameworks\/XCTest.framework\/XCTest' (no such file), '\/private\/preboot\/Cryptexes\/OS\/System\/Developer\/Library\/Frameworks\/XCTest.framework\/XCTest' (no such file), '\/System\/Developer\/usr\/lib\/XCTest.framework\/XCTest' (no such file), '\/private\/preboot\/Cryptexes\/OS\/System\/Developer\/usr\/lib\/XCTest.framework\/XCTest' (no such file), '\/Developer\/Library\/Frameworks\/XCTest.framework\/XCTest' (no such file), '\/private\/preboot\/Cryptexes\/OS\/Developer\/Library\/Frameworks\/XCTest.framework\/XCTest' (no such file), '\/Developer\/usr\/lib\/XCTest.framework\/XCTest' (no such file), '\/priv"]},


This could occur after a device reboot, but hasn't been connected to a host machine (debugger)
