### ISSUE TITLE
IOS 17 real device, can't launch wda

### ISSUE THREAD

**Issue by 7999** [appium/WebDriverAgent#905]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

build wda through xcode was succeed, but click the wda icon on device always flashback, and start appium test also failed due to wda failed issue

### Expected Behavior

launch wda succeed

### Minimal Reproducible Example

n.a, happen on real device

### Environment

- Operating system: mac os
- Appium server version (output of `appium --version`): 2.5.4
- Appium driver(s) and their version(s) (`appium driver list`):
- - xcuitest@7.16.2 [installed (npm)]
- uiautomator2 [not installed]
- mac2 [not installed]
- espresso [not installed]
- safari [not installed]
- gecko [not installed]
- chromium [not installed]

- Appium plugin(s) and their version(s) (`appium plugin list`):
- images [not installed]
- execute-driver [not installed]
- relaxed-caps [not installed]
- universal-xml [not installed]

- Node.js version (output of `node --version`): 16.20.0
- `npm` version (output of `npm --version`): 8.19.4
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iPad 17.4.1
- Real device or emulator/simulator: real device

### Further Information

[appium.log](https://github.com/appium/appium/files/15416164/appium.log)

**Comment by mykola-mokhnach** [comment]
Possible duplicate of https://github.com/appium/WebDriverAgent/issues/822

**Comment by KazuCocoa** [comment]
Did you remove `XC*` frameworks from the package as https://appium.github.io/appium-xcuitest-driver/latest/guides/run-preinstalled-wda/#additional-requirement-for-ios-17tvos17 ? If not and it was Xcode build installed one, the app may not launch, which is expected as the package structure.

**Comment by 7999** [comment]
@KazuCocoa
thanks for your hint, it works now

**Comment by DicerZ** [comment]
@KazuCocoa 
thanks a lot for your tip, it works the first time. But after rebooting the device, wda crashes.
The ips file indicates that: "reasons":["Library not loaded: @rpath\/XCTest.framework\/XCTest"]

**Comment by KazuCocoa** [comment]
In terms of iOS 17, with embedded frameworks way may fail to start outside xcodebuild.

**Comment by DicerZ** [comment]
> In terms of iOS 17, with embedded frameworks way may fail to start outside xcodebuild.

Thanks for your reply. 
The .app has not contain XC*.framework. It is a wonder that when the device connects to Mac, wda can launch as an app.

**Comment by KazuCocoa** [comment]
> when the device connects to Mac, wda can launch as an app.

Then, it sounds like Apple added such a protection on devices. For example, iOS allows to load the path only when the iOS thinks the device is connected to a service running on macOS.

**Comment by DicerZ** [comment]
> Then, it sounds like Apple added such a protection on devices. For example, iOS does not allow to load the path only when the iOS thinks the device is connected to a service running on macOS.

I expected it is a way to launch wda on Linux, but if it is like you said, that may not be a good idea right now.

**Comment by lnguyen234** [comment]
> > Then, it sounds like Apple added such a protection on devices. For example, iOS does not allow to load the path only when the iOS thinks the device is connected to a service running on macOS.
> 
> I expected it is a way to launch wda on Linux, but if it is like you said, that may not be a good idea right now.

Do we have any updates on this? I'm having the similar issue. Thank you
