### ISSUE TITLE
Can I support devices with ios 9.0?

### ISSUE THREAD

**Issue by jianghuihon** [appium/WebDriverAgent#911]
I need to support the system device of iOS9, I directly changed the lowest version to 9.0, but there is no screen during the automation, what should I do

**Comment by KazuCocoa** [comment]
https://appium.github.io/appium-xcuitest-driver/latest/installation/requirements/ is the basic compatible iOS/XCUITest driver versions. Lower OS versions may have API reference issues in WDA, especially XCUITest driver 4.27.2 is the last version for iOS 14 and lower.

 To make this WDA compatible with lower iOS versions, you might need to debug by yourself, or fork the old WDA only for lower iOS env for you.
