### ISSUE TITLE
webAgentRunner test running error? brower input http://192.168.199.143:8100 无法访问此网站

### ISSUE THREAD

**Issue by Edanaw** [appium/WebDriverAgent#927]
Running tests...
Test Suite 'All tests' started at 2024-08-01 22:58:00.279.
Test Suite 'WebDriverAgentRunner.xctest' started at 2024-08-01 22:58:00.280.
Test Suite 'UITestingUITests' started at 2024-08-01 22:58:00.280.
    t =      nans Suite Set Up
Couldn't write values for keys (
    KeyboardAutocorrection
) in CFPrefsPlistSource<0x303f92640> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
Not updating lastKnownShmemState in CFPrefsPlistSource<0x303f92640> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): 298 -> 298
Couldn't write values for keys (
    "KeyboardAutocorrection_changedAt"
) in CFPrefsPlistSource<0x303f92640> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
Not updating lastKnownShmemState in CFPrefsPlistSource<0x303f92640> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): 298 -> 298
Couldn't write values for keys (
    "KeyboardAutocorrection_buildAtChange"
) in CFPrefsPlistSource<0x303f92640> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
Not updating lastKnownShmemState in CFPrefsPlistSource<0x303f92640> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): 298 -> 298
Couldn't write values for keys (
    "KeyboardAutocorrection_previousValue"
) in CFPrefsPlistSource<0x303f92640> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
Not updating lastKnownShmemState in CFPrefsPlistSource<0x303f92640> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): 298 -> 298
Couldn't write values for keys (
    "KeyboardAutocorrection_analyzedAt"
) in CFPrefsPlistSource<0x303f92640> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
Not updating lastKnownShmemState in CFPrefsPlistSource<0x303f92640> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): 298 -> 298
Couldn't write values for keys (
    KeyboardPrediction
) in CFPrefsPlistSource<0x303f92640> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
Not updating lastKnownShmemState in CFPrefsPlistSource<0x303f92640> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): 298 -> 298
Couldn't write values for keys (
    KeyboardShowPredictionBar
) in CFPrefsPlistSource<0x303f92640> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
Not updating lastKnownShmemState in CFPrefsPlistSource<0x303f92640> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): 298 -> 298
Couldn't write values for keys (
    DidShowGestureKeyboardIntroduction
) in CFPrefsPlistSource<0x303f92640> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
Not updating lastKnownShmemState in CFPrefsPlistSource<0x303f92640> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): 298 -> 298
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s Start Test at 2024-08-01 22:58:00.318
    t =     0.00s Set Up
Built at Aug  1 2024 22:40:44
ServerURLHere->http://192.168.199.143:8100<-ServerURLHere

**Comment by KazuCocoa** [comment]
The log means the WDA is listening 8100 port on the device. you could access it via the URL or localhost via a port forward. Others can get ignored for now.
