### ISSUE TITLE
it's not working on iOS 13.6 iPhone 8

### ISSUE THREAD

**Issue by fengyunyongjie** [appium/WebDriverAgent#940]
2024-09-18 15:47:32.252447+0800 WebDriverAgentRunner-Runner[4694:83321] Running tests...
objc[4694]: Class LRUCache is implemented in both /System/Library/Frameworks/CFNetwork.framework/CFNetwork (0x1f6f37e60) and /private/var/containers/Bundle/Application/305E90A6-7E5D-498C-98FB-6419E113534A/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib (0x1034780d8). One of the two will be used. Which one is undefined.
Test Suite 'All tests' started at 2024-09-18 15:47:33.197
Test Suite 'WebDriverAgentRunner.xctest' started at 2024-09-18 15:47:33.198
Test Suite 'UITestingUITests' started at 2024-09-18 15:47:33.198
    t =      nans Suite Set Up
2024-09-18 15:47:33.215896+0800 WebDriverAgentRunner-Runner[4694:83321] [User Defaults] Couldn't write values for keys (
    KeyboardAutocorrection
) in CFPrefsPlistSource<0x2814b4d00> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2024-09-18 15:47:33.225154+0800 WebDriverAgentRunner-Runner[4694:83321] [User Defaults] Couldn't write values for keys (
    KeyboardPrediction
) in CFPrefsPlistSource<0x2814b4d00> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2024-09-18 15:47:33.225825+0800 WebDriverAgentRunner-Runner[4694:83321] [User Defaults] Couldn't write values for keys (
    KeyboardShowPredictionBar
) in CFPrefsPlistSource<0x2814b4d00> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2024-09-18 15:47:33.226363+0800 WebDriverAgentRunner-Runner[4694:83321] [User Defaults] Couldn't write values for keys (
    DidShowGestureKeyboardIntroduction
) in CFPrefsPlistSource<0x2814b4d00> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s Start Test at 2024-09-18 15:47:33.232
    t =     0.00s Set Up
2024-09-18 15:47:33.234868+0800 WebDriverAgentRunner-Runner[4694:83321] Built at Sep 13 2024 20:46:22
2024-09-18 15:47:33.252928+0800 WebDriverAgentRunner-Runner[4694:83321] ServerURLHere->http://192.168.1.177:8100<-ServerURLHere

**Comment by KazuCocoa** [comment]
> http://192.168.1.177:8100/<-ServerURLHere

It looks like it succeeded in launching WDA.

Btw, we no longer support iOS 13. The upstream currently supports iOS 15+.
https://appium.github.io/appium-xcuitest-driver/latest/installation/requirements/
