### ISSUE TITLE
WebDriverAgent is installed on an iPhone running iOS 17.6.1. However, upon restarting the iPhone, attempting to launch WebDriverAgent again will result in a crash.

### ISSUE THREAD

**Issue by bluestorm-faker** [appium/WebDriverAgent#944]
To launch the WebDriverAgentRunner package with xcrun devicectl device process launch for real devices it should not have Frameworks/XC** files.

For example, after building the WebDriverAgent with Xcode with proper sign, it generates /Users/<user>/Library/Developer/Xcode/DerivedData/WebDriverAgent-ezumztihszjoxgacuhatrhxoklbh/Build/Products/Debug-appletvos/WebDriverAgentRunner-Runner.app. Then you can remove Frameworks/XC** in WebDriverAgentRunner-Runner.app like rm Frameworks/WebDriverAgentRunner-Runner.app/XC**.

When I used this method for packaging, I successfully installed the application on my phone and it ran without any issues. However, after my phone restarted, clicking on the application did not launch it properly. I had to connect my device to XCode on an Apple computer and then click on the application again on my phone to launch it normally. Have you encountered this issue? I need my Apple phone to connect to a Windows computer to execute some code, but if WebDriverAgentRunner fails to run after restarting my Apple phone, causing the script execution to fail, do you have any plans to optimize for this issue in the future? Thank you!

**Comment by KazuCocoa** [comment]
Could you check the device log?

If the log had an error message such as no access to `Frameworks` on the phone (e.g. https://github.com/appium/WebDriverAgent/issues/896#issuecomment-2103873968), it is because the device is not allowed for developer usage. It could be iOS's restriction

**Comment by bluestorm-faker** [comment]
Thank you for your response, but I don't have any additional log content on my end. Perhaps what I described as a crash is incorrect. It should be said that if it fails to launch, you won't see the watermark indicating that the WebDriverAgent is running normally. Moreover, I didn't find any crash logs on my iPhone. I connected to the console of my iPhone and immediately clicked on the WebDriverAgent application after restarting it, but it failed to launch normally and display the WebDriverAgent watermark. At the same time, there were some outputs, but due to my limited expertise, I'm not sure if this output is helpful to you. If you click on the WebDriverAgent again after 1 or 2 minutes, it will launch normally. If you don't connect to an Apple device, the application will not run normally after restarting the phone (without the WebDriverAgent watermark output), and the console will display the following output.
=========
'app<com.facebook.WebDriverAgentRunner.xctrunner22(E7FF18A7-1DAB-4DE5-8613-BD40D9DE0894)>' Constructed job description:
<dictionary: 0x690b34660> { count = 19, transaction: 0, voucher = 0x0, contents =
        "ProcessType" => <string: 0x690acfe10> { length = 3, contents = "App" }
        "EnableTransactions" => <bool: 0x202ad0390>: false
        "_ManagedBy" => <string: 0x690acf9c0> { length = 22, contents = "com.apple.runningboard" }
        "_ResourceCoalition" => <string: 0x690acda70> { length = 88, contents = "app<com.facebook.WebDriverAgentRunner.xctrunner22(E7FF18A7-1DAB-4DE5-8613-BD40D9DE0894)>" }
        "CFBundleIdentifier" => <string: 0x690acdb00> { length = 45, contents = "com.facebook.WebDriverAgentRunner.xctrunner22" }
        "ThrottleInterval" => <int64: 0xba398235eaf59447>: 2147483647
        "PersonaEnterprise" => <int64: 0xba398236150a74ff>: 1000
        "MachServices" => <dictionary: 0x690b34540> { count = 0, transaction: 0, voucher = 0x0, contents =
        }
        "EnablePressuredExit" => <bool: 0x202ad0390>: false
        "InitialTaskRole" => <int64: 0xba398236150a6bb7>: 1
        "UserName" => <string: 0x690acfa50> { length = 6, contents = "mobile" }
        "EnvironmentVariables" => <dictionary: 0x690b343c0> { count = 3, transaction: 0, voucher = 0x0, contents =
                "TMPDIR" => <string: 0x690acfcc0> { length = 88, contents = "/private/var/mobile/Containers/Data/Application/F8EE9814-2E60-49FA-AC59-0EDD9B152A4E/tmp" }
                "HOME" => <string: 0x690ace070> { length = 84, contents = "/private/var/mobile/Containers/Data/Application/F8EE9814-2E60-49FA-AC59-0EDD9B152A4E" }
                "CFFIXED_USER_HOME" => <string: 0x690accf90> { length = 84, contents = "/private/var/mobile/Containers/Data/Application/F8EE9814-2E60-49FA-AC59-0EDD9B152A4E" }
        }
        "_AdditionalProperties" => <dictionary: 0x690b34120> { count = 1, transaction: 0, voucher = 0x0, contents =
                "RunningBoard" => <dictionary: 0x690b34420> { count = 3, transaction: 0, voucher = 0x0, contents =
                        "Managed" => <bool: 0x202ad0370>: true
                        "RunningBoardLaunchedIdentity" => <dictionary: 0x690b34060> { count = 3, transaction: 0, voucher = 0x0, contents =
                                "TYPE" => <int64: 0xba398236150a6baf>: 2
                                "EAI" => <string: 0x690acff00> { length = 45, contents = "com.facebook.WebDriverAgentRunner.xctrunner22" }
                                "PERS" => <string: 0x690acfc60> { length = 36, contents = "E7FF18A7-1DAB-4DE5-8613-BD40D9DE0894" }
                        }
                        "RunningBoardLaunched" => <bool: 0x202ad0370>: true
                }
        }
        "ExitTimeOut" => <int64: 0xba398236150a6bb7>: 1
        "Label" => <string: 0x690acf930> { length = 79, contents = "UIKitApplication:com.facebook.WebDriverAgentRunner.xctrunner22[be44][rb-legacy]" }
        "MaterializeDatalessFiles" => <bool: 0x202ad0370>: true
        "_LaunchType" => <int64: 0xba398236150a6ba7>: 3
        "ProgramArguments" => <array: 0x690acf750> { count = 1, capacity = 8, contents =
                0: <string: 0x690acfde0> { length = 131, contents = "/var/containers/Bundle/Application/FD4E303C-1E32-4301-AC0C-64CF47ACB898/WebDriverAgentRunner-Runner.app/WebDriverAgentRunner-Runner" }
        }
        "Program" => <string: 0x690acec70> { length = 131, contents = "/var/containers/Bundle/Application/FD4E303C-1E32-4301-AC0C-64CF47ACB898/WebDriverAgentRunner-Runner.app/WebDriverAgentRunner-Runner" }
}
=========
![11](https://github.com/user-attachments/assets/a171930c-13e3-4274-8a88-a83a4fc2a5f2)

**Comment by KazuCocoa** [comment]
I could reproduce the behavior. It had not library found error as below. This is what I wanted to address in https://github.com/appium/WebDriverAgent/issues/944#issuecomment-2407823761.

<img width="1441" alt="Screenshot 2024-10-12 at 11 33 57 PM" src="https://github.com/user-attachments/assets/62097ad6-441e-46e0-a75b-876177c97bcd">


This occurs when non-device mount occurred. Some 3rd party libs such as https://github.com/doronz88/pymobiledevice3 would help to mount images with `pymobiledevice3 mounter auto-mount` if you would avoid launching Xcode.

**Comment by bluestorm-faker** [comment]
> I could reproduce the behavior. It had not library found error as below. This is what I wanted to address in [#944 (comment)](https://github.com/appium/WebDriverAgent/issues/944#issuecomment-2407823761).我可以重现这种行为。它未在库中找到如下错误。这就是我想在 [#944 （评论）](https://github.com/appium/WebDriverAgent/issues/944#issuecomment-2407823761) 中解决的问题。
> 
> <img alt="Screenshot 2024-10-12 at 11 33 57 PM" width="1441" src="https://private-user-images.githubusercontent.com/5511591/376012789-62097ad6-441e-46e0-a75b-876177c97bcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NzkxOTUsIm5iZiI6MTcyODg3ODg5NSwicGF0aCI6Ii81NTExNTkxLzM3NjAxMjc4OS02MjA5N2FkNi00NDFlLTQ2ZTAtYTc1Yi04NzYxNzdjOTdiY2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMDQwODE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTJmYzMzYWRhZmZiNDU4ZDA5YWUwZDBkNWNiYzljMGMxZGEzNTA5YjFiNjc0YjU1YzBhOTc1ZTE1NjM5ZWE5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._goTGLBFcnxOYzCKz_YBSzjP64XBHacpPYWPQM8kSxA">
> This occurs when non-device mount occurred. Some 3rd party libs such as https://github.com/doronz88/pymobiledevice3 would help to mount images with `pymobiledevice3 mounter auto-mount` if you would avoid launching Xcode.当发生非设备挂载时，会发生这种情况。如果您避免启动 Xcode，一些第三方库（例如 https://github.com/doronz88/pymobiledevice3）将有助于挂载映像。

Thank you very much. I have solved the problem using this method.

**Comment by bluestorm-faker** [comment]
> I could reproduce the behavior. It had not library found error as below. This is what I wanted to address in [#944 (comment)](https://github.com/appium/WebDriverAgent/issues/944#issuecomment-2407823761).
> 
> <img alt="Screenshot 2024-10-12 at 11 33 57 PM" width="1441" src="https://private-user-images.githubusercontent.com/5511591/376012789-62097ad6-441e-46e0-a75b-876177c97bcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4ODY3MzEsIm5iZiI6MTcyODg4NjQzMSwicGF0aCI6Ii81NTExNTkxLzM3NjAxMjc4OS02MjA5N2FkNi00NDFlLTQ2ZTAtYTc1Yi04NzYxNzdjOTdiY2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMDYxMzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDhjNDdiNDJlOGVkOWYzNTYwYTNmNTg1Y2M2Yzk1ZjMwZDYwZGVjYjNmYmJjMDA2NmE4ZmVjZDFjZDVmNjI1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.PyMLuV4CDQHiHhNU4wzaoceScifcTXBSMZvFbSj7ysY">
> This occurs when non-device mount occurred. Some 3rd party libs such as https://github.com/doronz88/pymobiledevice3 would help to mount images with if you would avoid launching Xcode.`pymobiledevice3 mounter auto-mount`

Thank you very much. I have solved the problem using this method.

**Comment by Hubbard1999** [comment]
设备重启后，wda应用需要重新加载开发者镜像，有两种方式可以恢复
1、打开xcode
2、执行go-ios的ios image auto命令
